"""temp_migration

Revision ID: 8bec0b5c60d5
Revises: 4f620f0b8e09
Create Date: 2025-03-20 13:51:27.573617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8bec0b5c60d5"
down_revision: Union[str, None] = "4f620f0b8e09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("temp_email", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "temp_email")
    # ### end Alembic commands ###
