"""temp_migration

Revision ID: e78220e1dd03
Revises: 49935c4c489b
Create Date: 2025-03-31 13:02:33.666025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e78220e1dd03"
down_revision: Union[str, None] = "49935c4c489b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("transmision", sa.String(), nullable=True))
    op.add_column("cars", sa.Column("vehicle_type", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cars", "vehicle_type")
    op.drop_column("cars", "transmision")
    # ### end Alembic commands ###
