MAKES_AND_MODELS = {
  "acura": {
    "original": "Acura",
    "models": {
      "adx": "ADX",
      "cl": "CL",
      "csx": "CSX",
      "el": "EL",
      "enclave": "Enclave",
      "ilx": "ILX",
      "integra": "Integra",
      "legend": "Legend",
      "mdx": "MDX",
      "nsx": "NSX",
      "rdx": "RDX",
      "rl": "RL",
      "rlx": "RLX",
      "rsx": "RSX",
      "slx": "SLX",
      "tl": "TL",
      "tlx": "TLX",
      "tsx": "TSX",
      "zdx": "ZDX"
    }
  },
  "alfa romeo": {
    "original": "Alfa Romeo",
    "models": {
      "159": "159",
      "164": "164",
      "4c": "4C",
      "gtv": "GTV",
      "giulia": "Giulia",
      "giulietta": "Giulietta",
      "milano": "Milano",
      "mito": "Mito",
      "spider": "Spider",
      "stelvio": "Stelvio",
      "tonale": "Tonale"
    }
  },
  "alumacraft": {
    "original": "Alumacraft",
    "models": {
      "16jt": "16jt",
      "boat": "Boat",
      "fishing boat": "Fishing Boat"
    }
  },
  "apex": {
    "original": "Apex",
    "models": {
      "quest 816": "Quest 816"
    }
  },
  "aprilia": {
    "original": "Aprilia",
    "models": {
      "dorsoduro": "DORSODURO",
      "mana 850": "MANA 850",
      "rs": "RS",
      "rsv": "RSV",
      "scarabeo": "SCARABEO",
      "shiver": "SHIVER",
      "tuareg 660": "TUAREG 660",
      "tuono": "TUONO",
      "tuono 660": "TUONO 660",
      "tuono v4": "TUONO V4"
    }
  },
  "aquasport": {
    "original": "Aquasport",
    "models": {
      "osprey": "Osprey"
    }
  },
  "arctic cat": {
    "original": "Arctic Cat",
    "models": {
      "atv": "ATV",
      "prowler": "Prowler",
      "snowmobile": "Snowmobile",
      "trv": "TRV",
      "wildcat": "Wildcat"
    }
  },
  "aston martin": {
    "original": "Aston Martin",
    "models": {
      "db11": "DB11",
      "db7": "DB7",
      "db9": "DB9",
      "dbs": "DBS",
      "dbx": "DBX",
      "dbx707": "DBX707",
      "one-77": "One-77",
      "rapide": "Rapide",
      "v12 vantage": "V12 Vantage",
      "v8 vantage": "V8 Vantage",
      "vanquish": "Vanquish",
      "vantage": "Vantage",
      "virage": "Virage"
    }
  },
  "audi": {
    "original": "Audi",
    "models": {
      "a1": "A1",
      "a3": "A3",
      "a3 quattro": "A3 Quattro",
      "a3 sportback e-tron": "A3 Sportback e-tron",
      "a3 e-tron": "A3 e-tron",
      "a4": "A4",
      "a4 quattro": "A4 Quattro",
      "a4 allroad": "A4 allroad",
      "a5": "A5",
      "a5 quattro": "A5 Quattro",
      "a5 sportback": "A5 Sportback",
      "a6": "A6",
      "a6 quattro": "A6 Quattro",
      "a6 allroad": "A6 allroad",
      "a7": "A7",
      "a7 quattro": "A7 Quattro",
      "a7 sportback": "A7 Sportback",
      "a8": "A8",
      "a8 quattro": "A8 Quattro",
      "q2": "Q2",
      "q2 quattro": "Q2 Quattro",
      "q3": "Q3",
      "q3 quattro": "Q3 Quattro",
      "q4 e-tron": "Q4 e-tron",
      "q4 e-tron sportback": "Q4 e-tron Sportback",
      "q5": "Q5",
      "q5 phev": "Q5 PHEV",
      "q5 sportback": "Q5 Sportback",
      "q6 e-tron": "Q6 e-tron",
      "q7": "Q7",
      "q8": "Q8",
      "r8": "R8",
      "rs q3": "RS Q3",
      "rs q8": "RS Q8",
      "rs e-tron gt": "RS e-tron GT",
      "rs3": "RS3",
      "rs4": "RS4",
      "rs5": "RS5",
      "rs5 sportback": "RS5 Sportback",
      "rs6": "RS6",
      "rs6 avant": "RS6 Avant",
      "rs7": "RS7",
      "rs7 sportback": "RS7 Sportback",
      "s3": "S3",
      "s4": "S4",
      "s5": "S5",
      "s5 sportback": "S5 Sportback",
      "s6": "S6",
      "s7": "S7",
      "s7 sportback": "S7 Sportback",
      "s8": "S8",
      "sq5": "SQ5",
      "sq5 sportback": "SQ5 Sportback",
      "sq7": "SQ7",
      "sq8": "SQ8",
      "tt": "TT",
      "tt quattro": "TT Quattro",
      "tt rs": "TT RS",
      "tt rs quattro": "TT RS Quattro",
      "tts": "TTS",
      "tts quattro": "TTS Quattro",
      "allroad": "allroad",
      "e-tron": "e-tron",
      "e-tron gt": "e-tron GT",
      "e-tron s": "e-tron S",
      "e-tron s sportback": "e-tron S Sportback",
      "e-tron sportback": "e-tron Sportback"
    }
  },
  "axis": {
    "original": "Axis",
    "models": {
      "maverick x": "Maverick X"
    }
  },
  "bmw": {
    "original": "BMW",
    "models": {
      "1 series": "1 Series",
      "2 series": "2 Series",
      "3 series": "3 Series",
      "4 series": "4 Series",
      "5 series": "5 Series",
      "6 series": "6 Series",
      "7 series": "7 Series",
      "8 series": "8 Series",
      "activehybrid 3": "ActiveHybrid 3",
      "activehybrid 5": "ActiveHybrid 5",
      "alpina b6 gran coupe": "Alpina B6 Gran Coupe",
      "alpina b7": "Alpina B7",
      "alpina b7 xdrive": "Alpina B7 xDrive",
      "alpina b8 gran coupe": "Alpina B8 Gran Coupe",
      "alpina xb7": "Alpina XB7",
      "c": "C",
      "c 650": "C 650",
      "f 650": "F 650",
      "f 700": "F 700",
      "f 750": "F 750",
      "f 800": "F 800",
      "f 850": "F 850",
      "f 900": "F 900",
      "g 310": "G 310",
      "g 650": "G 650",
      "i series": "I Series",
      "k 1100": "K 1100",
      "k 1200": "K 1200",
      "k 1300": "K 1300",
      "k 1600": "K 1600",
      "m": "M",
      "m 1000": "M 1000",
      "m2": "M2",
      "m235i": "M235i",
      "m235i xdrive": "M235i xDrive",
      "m240i": "M240i",
      "m240i xdrive": "M240i xDrive",
      "m3": "M3",
      "m340i": "M340i",
      "m340i xdrive": "M340i xDrive",
      "m4": "M4",
      "m440i": "M440i",
      "m440i gran coupe": "M440i Gran Coupe",
      "m440i xdrive": "M440i xDrive",
      "m5": "M5",
      "m550i xdrive": "M550i xDrive",
      "m6": "M6",
      "m6 gran coupe": "M6 Gran Coupe",
      "m7": "M7",
      "m760i xdrive": "M760i xDrive",
      "m8": "M8",
      "m8 gran coupe": "M8 Gran Coupe",
      "m850i xdrive": "M850i xDrive",
      "m850i xdrive gran coupe": "M850i xDrive Gran Coupe",
      "r": "R",
      "r 1100": "R 1100",
      "r 1150": "R 1150",
      "r 1200": "R 1200",
      "r 1250": "R 1250",
      "r 18": "R 18",
      "s 1000": "S 1000",
      "x1": "X1",
      "x2": "X2",
      "x3": "X3",
      "x4": "X4",
      "x5": "X5",
      "x6": "X6",
      "x7": "X7",
      "xm": "XM",
      "z3": "Z3",
      "z4": "Z4",
      "i3": "i3",
      "i3s": "i3s",
      "i4": "i4",
      "i5": "i5",
      "i7": "i7",
      "i8": "i8",
      "ix": "iX"
    }
  },
  "baha": {
    "original": "Baha",
    "models": {
      "boat w/trl": "Boat W/trl"
    }
  },
  "baja": {
    "original": "Baja",
    "models": {
      "boat": "Boat",
      "other": "Other"
    }
  },
  "baja 272": {
    "original": "Baja 272",
    "models": {
      "baja 272": "Baja 272"
    }
  },
  "barletta": {
    "original": "Barletta",
    "models": {
      "pontoon": "Pontoon",
      "tritoon": "Tritoon"
    }
  },
  "bass": {
    "original": "Bass",
    "models": {
      "boat": "Boat"
    }
  },
  "bayliner": {
    "original": "Bayliner",
    "models": {
      "2003 trophy series": "2003 Trophy Series",
      "boat": "Boat",
      "capri": "Capri",
      "ciera": "Ciera",
      "other": "Other"
    }
  },
  "bennington": {
    "original": "Bennington",
    "models": {
      "21slx": "21slx",
      "bennington 20ss": "Bennington 20ss",
      "bennington 22lsb": "Bennington 22lsb",
      "other": "Other"
    }
  },
  "bentley": {
    "original": "Bentley",
    "models": {
      "arnage": "Arnage",
      "azure": "Azure",
      "bentayga": "Bentayga",
      "continental": "Continental",
      "flying spur": "Flying Spur",
      "mulsanne": "Mulsanne",
      "turbo r": "Turbo R"
    }
  },
  "big dog": {
    "original": "Big Dog",
    "models": {
      "chopper": "Chopper",
      "k9": "K9",
      "wolf": "Wolf"
    }
  },
  "blue bird": {
    "original": "Blue Bird",
    "models": {
      "school bus / transit bus": "School Bus / Transit Bus"
    }
  },
  "buell": {
    "original": "Buell",
    "models": {
      "1125": "1125",
      "blast": "BLAST",
      "cyclone": "CYCLONE",
      "firebolt": "FIREBOLT",
      "lightning": "LIGHTNING",
      "ulysses": "ULYSSES"
    }
  },
  "bugatti": {
    "original": "Bugatti",
    "models": {
      "chiron": "Chiron",
      "divo": "Divo",
      "veyron 16.4": "Veyron 16.4"
    }
  },
  "buick": {
    "original": "Buick",
    "models": {
      "allure": "Allure",
      "cascada": "Cascada",
      "century": "Century",
      "electra": "Electra",
      "enclave": "Enclave",
      "enclave avenir": "Enclave Avenir",
      "encore": "Encore",
      "encore gx": "Encore GX",
      "envision": "Envision",
      "envista": "Envista",
      "lacrosse": "LaCrosse",
      "lesabre": "LeSabre",
      "lucerne": "Lucerne",
      "park avenue": "Park Avenue",
      "rainier": "Rainier",
      "reatta": "Reatta",
      "regal": "Regal",
      "regal sportback": "Regal Sportback",
      "regal tourx": "Regal TourX",
      "rendezvous": "Rendezvous",
      "riviera": "Riviera",
      "roadmaster": "Roadmaster",
      "skylark": "Skylark",
      "terraza": "Terraza",
      "verano": "Verano"
    }
  },
  "cadillac": {
    "original": "Cadillac",
    "models": {
      "ats": "ATS",
      "allante": "Allante",
      "brougham": "Brougham",
      "ct4": "CT4",
      "ct5": "CT5",
      "ct6": "CT6",
      "cts": "CTS",
      "calais": "Calais",
      "catera": "Catera",
      "commercial chassis": "Commercial Chassis",
      "dts": "DTS",
      "deville": "Deville",
      "elr": "ELR",
      "eldorado": "Eldorado",
      "escalade": "Escalade",
      "escalade esv": "Escalade ESV",
      "escalade ext": "Escalade EXT",
      "escalade hybrid": "Escalade Hybrid",
      "fleetwood": "Fleetwood",
      "hearse": "Hearse",
      "lyriq": "LYRIQ",
      "optiq": "OPTIQ",
      "professional chassis": "Professional Chassis",
      "srx": "SRX",
      "sts": "STS",
      "seville": "Seville",
      "vistiq": "Vistiq",
      "xlr": "XLR",
      "xt4": "XT4",
      "xt5": "XT5",
      "xt6": "XT6",
      "xts": "XTS"
    }
  },
  "can-am": {
    "original": "Can-Am",
    "models": {
      "atv": "ATV",
      "commander": "Commander",
      "defender": "Defender",
      "maverick": "Maverick",
      "maverick trail": "MAVERICK TRAIL",
      "maverick x3": "MAVERICK X3",
      "maverick x3 max": "MAVERICK X3 MAX",
      "outlander": "Outlander",
      "renegade": "RENEGADE",
      "ryker": "RYKER",
      "spyder roadster": "SPYDER ROADSTER",
      "spyder": "Spyder"
    }
  },
  "caravelle": {
    "original": "Caravelle",
    "models": {
      "212 bowrid": "212 Bowrid",
      "230 seahawk": "230 Seahawk"
    }
  },
  "cfmoto": {
    "original": "Cfmoto",
    "models": {
      "c force": "C Force",
      "u force": "U Force",
      "zforce 800": "ZFORCE 800"
    }
  },
  "chaparral": {
    "original": "Chaparral",
    "models": {
      "183ss": "183ss",
      "boat": "Boat",
      "chaparral 280 signat": "Chaparral 280 Signat",
      "sunesta 244 xtreme": "Sunesta 244 Xtreme"
    }
  },
  "chevrolet": {
    "original": "Chevrolet",
    "models": {
      "2500": "2500",
      "3500": "3500",
      "4500": "4500",
      "astro": "Astro",
      "avalanche": "Avalanche",
      "aveo": "Aveo",
      "aveo5": "Aveo5",
      "beat": "Beat",
      "bel air": "Bel Air",
      "beretta": "Beretta",
      "blazer": "Blazer",
      "bolt euv": "Bolt EUV",
      "bolt ev": "Bolt EV",
      "c/k 1500": "C/K 1500",
      "c/k 2500": "C/K 2500",
      "c/k 3500": "C/K 3500",
      "c/k4500": "C/K4500",
      "c/k5500": "C/K5500",
      "c10": "C10",
      "c1500": "C1500",
      "c20": "C20",
      "c2500": "C2500",
      "c30": "C30",
      "c3500": "C3500",
      "c3500 chassis": "C3500 Chassis",
      "c4500": "C4500",
      "c5500": "C5500",
      "c65": "C65",
      "c7500": "C7500",
      "cc4500": "CC4500",
      "cc5500": "CC5500",
      "cc6500": "CC6500",
      "camaro": "Camaro",
      "caprice": "Caprice",
      "captiva": "Captiva",
      "captiva sport": "Captiva Sport",
      "cavalier": "Cavalier",
      "celebrity": "Celebrity",
      "chevelle": "Chevelle",
      "chevy": "Chevy",
      "cheyenne": "Cheyenne",
      "city express": "City Express",
      "classic": "Classic",
      "cobalt": "Cobalt",
      "colorado": "Colorado",
      "corsica": "Corsica",
      "corvair": "Corvair",
      "corvette": "Corvette",
      "corvette stingray": "Corvette Stingray",
      "cruze": "Cruze",
      "cruze limited": "Cruze Limited",
      "cruze ng": "Cruze NG",
      "delray": "Delray",
      "el camino": "El Camino",
      "equinox": "Equinox",
      "express 1500": "Express 1500",
      "express 2500": "Express 2500",
      "express 3500": "Express 3500",
      "express 4500": "Express 4500",
      "express cargo": "Express Cargo",
      "express pasajeros": "Express Pasajeros",
      "g10": "G10",
      "g20": "G20",
      "g30": "G30",
      "gmt": "GMT",
      "geo prizm": "Geo Prizm",
      "groove": "Groove",
      "hhr": "HHR",
      "impala": "Impala",
      "impala limited": "Impala Limited",
      "k10": "K10",
      "k20": "K20",
      "kodiak": "Kodiak",
      "lcf 3500": "LCF 3500",
      "lcf 3500hd": "LCF 3500HD",
      "lcf 4500": "LCF 4500",
      "lcf 4500hd": "LCF 4500HD",
      "lcf 4500xd": "LCF 4500XD",
      "lcf 5500hd": "LCF 5500HD",
      "lcf 5500xd": "LCF 5500XD",
      "lcf 6500xd": "LCF 6500XD",
      "lumina": "Lumina",
      "malibu": "Malibu",
      "malibu limited": "Malibu Limited",
      "matiz": "Matiz",
      "metro": "Metro",
      "monte carlo": "Monte Carlo",
      "nova": "Nova",
      "nuevo aveo": "Nuevo Aveo",
      "onix": "Onix",
      "optra": "Optra",
      "orlando": "Orlando",
      "p30": "P30",
      "prizm": "Prizm",
      "r30": "R30",
      "s truck": "S Truck",
      "s-10": "S-10",
      "s10": "S10",
      "ss": "SS",
      "ssr": "SSR",
      "silverado": "Silverado",
      "silverado 1500": "Silverado 1500",
      "silverado 2500": "Silverado 2500",
      "silverado 3500": "Silverado 3500",
      "sonic": "Sonic",
      "spark": "Spark",
      "spark classic": "Spark Classic",
      "spark ev": "Spark EV",
      "suburban": "Suburban",
      "suburban 1500": "Suburban 1500",
      "suburban 2500": "Suburban 2500",
      "suburban 3500 hd": "Suburban 3500 HD",
      "tahoe": "Tahoe",
      "tilt mstr": "Tilt Mstr",
      "tornado": "Tornado",
      "tornado van": "Tornado Van",
      "tracker": "Tracker",
      "trailblazer": "Trailblazer",
      "traverse": "Traverse",
      "trax": "Trax",
      "uplander": "Uplander",
      "venture": "Venture",
      "volt": "Volt",
      "w4500 tiltmaster": "W4500 Tiltmaster",
      "w5500 tiltmaster": "W5500 Tiltmaster"
    }
  },
  "chrysler": {
    "original": "Chrysler",
    "models": {
      "200": "200",
      "300": "300",
      "300m": "300M",
      "aspen": "Aspen",
      "cirrus": "Cirrus",
      "concorde": "Concorde",
      "crossfire": "Crossfire",
      "fifth avenue": "Fifth Avenue",
      "grand caravan": "Grand Caravan",
      "grand voyager": "Grand Voyager",
      "imperial": "Imperial",
      "intrepid": "Intrepid",
      "lhs": "LHS",
      "lebaron": "LeBaron",
      "neon": "Neon",
      "new yorker": "New Yorker",
      "newport": "Newport",
      "pt cruiser": "PT Cruiser",
      "pacifica": "Pacifica",
      "sebring": "Sebring",
      "town & country": "Town & Country",
      "voyager": "Voyager"
    }
  },
  "dodge": {
    "original": "Dodge",
    "models": {
      "2500 sprinter": "2500 Sprinter",
      "600": "600",
      "a100": "A100",
      "aries": "Aries",
      "atos": "Atos",
      "attitude": "Attitude",
      "avenger": "Avenger",
      "b series": "B Series",
      "caliber": "Caliber",
      "caravan": "Caravan",
      "challenger": "Challenger",
      "charger": "Charger",
      "colt": "Colt",
      "coronet": "Coronet",
      "d-series": "D-Series",
      "d50": "D50",
      "dakota": "Dakota",
      "dart": "Dart",
      "durango": "Durango",
      "dynasty": "Dynasty",
      "freightliner sprinter 2500": "Freightliner Sprinter 2500",
      "freightliner sprinter 2500/3500": "Freightliner Sprinter 2500/3500",
      "grand caravan": "Grand Caravan",
      "h100": "H100",
      "h100 van": "H100 Van",
      "hornet": "Hornet",
      "intrepid": "Intrepid",
      "journey": "Journey",
      "magnum": "Magnum",
      "motorhome": "Motorhome",
      "neon": "Neon",
      "nitro": "Nitro",
      "promaster": "Promaster",
      "promaster 1500": "Promaster 1500",
      "promaster 2500": "Promaster 2500",
      "promaster 3500": "Promaster 3500",
      "promaster city": "Promaster City",
      "r1500": "R1500",
      "ram": "Ram",
      "ram 1500": "Ram 1500",
      "ram 2500": "Ram 2500",
      "ram 3500": "Ram 3500",
      "ram 4000": "Ram 4000",
      "ram 4500": "Ram 4500",
      "ram 5500": "Ram 5500",
      "ram promaster 1500": "Ram Promaster 1500",
      "ram promaster 2500": "Ram Promaster 2500",
      "ram srt10": "Ram Srt10",
      "ram truck": "Ram Truck",
      "ram van": "Ram Van",
      "ram wagon": "Ram Wagon",
      "ramcharger": "Ramcharger",
      "shadow": "Shadow",
      "spirit": "Spirit",
      "sprinter": "Sprinter",
      "stealth": "Stealth",
      "stratus": "Stratus",
      "traveler": "Traveler",
      "truck": "Truck",
      "van": "Van",
      "viper": "Viper",
      "vision": "Vision",
      "w-series": "W-Series",
      "i10": "i10"
    }
  },
  "doral": {
    "original": "Doral",
    "models": {
      "other": "Other"
    }
  },
  "ducati": {
    "original": "Ducati",
    "models": {
      "1098": "1098",
      "1198": "1198",
      "748": "748",
      "848": "848",
      "desert x": "DESERT X",
      "diavel": "DIAVEL",
      "hypermotard": "HYPERMOTARD",
      "m900": "M900",
      "monster": "MONSTER",
      "multistrada": "MULTISTRADA",
      "panigale": "PANIGALE",
      "scrambler": "SCRAMBLER",
      "st4": "ST4",
      "streetfighter": "STREETFIGHTER",
      "superbike": "SUPERBIKE",
      "supersport": "SUPERSPORT",
      "xdiavel": "XDIAVEL"
    }
  },
  "ferrari": {
    "original": "Ferrari",
    "models": {
      "296 gtb": "296 GTB",
      "348": "348",
      "360": "360",
      "400": "400",
      "456": "456",
      "458 italia": "458 Italia",
      "458 speciale": "458 Speciale",
      "458 spider": "458 Spider",
      "488 gtb": "488 GTB",
      "488 pista": "488 Pista",
      "488 pista spider": "488 Pista Spider",
      "488 spider": "488 Spider",
      "599 gtb": "599 GTB",
      "599 gto": "599 GTO",
      "612 scaglietti": "612 Scaglietti",
      "812 gts": "812 GTS",
      "812 superfast": "812 Superfast",
      "california": "California",
      "california t": "California T",
      "f12 berlinetta": "F12 Berlinetta",
      "f12tdf": "F12tdf",
      "f430": "F430",
      "f8 spider": "F8 Spider",
      "f8 tributo": "F8 Tributo",
      "ff": "FF",
      "gtc4lusso": "GTC4Lusso",
      "gtc4lusso t": "GTC4Lusso T",
      "laferrari": "LaFerrari",
      "mondial": "Mondial",
      "portofino": "Portofino",
      "portofino m": "Portofino M",
      "purosangue": "Purosangue",
      "roma": "Roma",
      "sf90 spider": "SF90 Spider",
      "sf90 stradale": "SF90 Stradale"
    }
  },
  "fiat": {
    "original": "Fiat",
    "models": {
      "124 spider": "124 Spider",
      "500": "500",
      "500c": "500C",
      "500e": "500E",
      "500l": "500L",
      "500x": "500X",
      "albea": "Albea",
      "argo": "Argo",
      "ducato": "Ducato",
      "jolly": "JOLLY",
      "linea": "Linea",
      "mobi": "Mobi",
      "palio": "Palio",
      "panda": "Panda",
      "punto": "Punto",
      "spider": "Spider",
      "strada": "Strada",
      "uno": "Uno"
    }
  },
  "fisker": {
    "original": "Fisker",
    "models": {
      "karma": "Karma",
      "ocean": "OCEAN"
    }
  },
  "ford": {
    "original": "Ford",
    "models": {
      "aerostar": "Aerostar",
      "bronco": "Bronco",
      "bronco sport": "Bronco Sport",
      "c-max": "C-Max",
      "club wagon": "Club Wagon",
      "contour": "Contour",
      "crown victoria": "Crown Victoria",
      "drw super duty": "DRW Super Duty",
      "e-150": "E-150",
      "e-250": "E-250",
      "e-350": "E-350",
      "e-450": "E-450",
      "e-450 super duty": "E-450 Super Duty",
      "e-transit-350": "E-Transit-350",
      "ecosport": "EcoSport",
      "econoline": "Econoline",
      "econoline e350": "Econoline E350",
      "econoline wagon": "Econoline Wagon",
      "edge": "Edge",
      "escape": "Escape",
      "escape hybrid": "Escape Hybrid",
      "escort": "Escort",
      "excursion": "Excursion",
      "expedition": "Expedition",
      "explorer": "Explorer",
      "explorer sport trac": "Explorer Sport Trac",
      "f": "F",
      "f-150": "F-150",
      "f-150 lightning": "F-150 Lightning",
      "f-250": "F-250",
      "f-250 super duty": "F-250 Super Duty",
      "f-350": "F-350",
      "f-350 super duty": "F-350 Super Duty",
      "f-450": "F-450",
      "f-450 super duty": "F-450 Super Duty",
      "f-550": "F-550",
      "f-550 chassis": "F-550 Chassis",
      "f-550 super duty": "F-550 Super Duty",
      "f-59 commercial stripped": "F-59 Commercial Stripped",
      "f-600": "F-600",
      "f-650": "F-650",
      "f-750": "F-750",
      "f100": "F100",
      "f53": "F53",
      "f530": "F530",
      "f59": "F59",
      "f700": "F700",
      "f800": "F800",
      "fairlane": "Fairlane",
      "festiva": "Festiva",
      "fiesta": "Fiesta",
      "five hundred": "Five Hundred",
      "flex": "Flex",
      "focus": "Focus",
      "freestar": "Freestar",
      "freestyle": "Freestyle",
      "fusion": "Fusion",
      "gt": "GT",
      "galaxie": "Galaxie",
      "l-series": "L-Series",
      "lcf": "LCF",
      "lgt": "LGT",
      "ltd": "LTD",
      "low cab forward": "Low Cab Forward",
      "maverick": "Maverick",
      "mustang": "Mustang",
      "mustang mach-e": "Mustang Mach-E",
      "police interceptor utility": "Police Interceptor Utility",
      "ranchero": "Ranchero",
      "ranger": "Ranger",
      "shelby": "SHELBY",
      "srw super duty": "SRW Super Duty",
      "super club wagon": "Super Club Wagon",
      "t bird": "T Bird",
      "taurus": "Taurus",
      "tempo": "Tempo",
      "thunderbird": "Thunderbird",
      "transit": "Transit",
      "transit connect": "Transit Connect",
      "transit-150": "Transit-150",
      "transit-250": "Transit-250",
      "transit-350": "Transit-350",
      "vehicle light duty": "Vehicle Light Duty",
      "windstar": "Windstar"
    }
  },
  "freightliner": {
    "original": "Freightliner",
    "models": {
      "122sd": "122sd",
      "cascadia 125": "Cascadia 125",
      "cascadia 126": "Cascadia 126",
      "chassis": "Chassis",
      "conventional": "Conventional",
      "m2 106": "M2 106"
    }
  },
  "gmc": {
    "original": "GMC",
    "models": {
      "3500": "3500",
      "4000": "4000",
      "acadia": "Acadia",
      "c-series": "C-Series",
      "c/k/r1500": "C/K/R1500",
      "c/k/r2500": "C/K/R2500",
      "c/k/r5500": "C/K/R5500",
      "c/k/r7500": "C/K/R7500",
      "c1500": "C1500",
      "c2500": "C2500",
      "c4500": "C4500",
      "c5500": "C5500",
      "c6500": "C6500",
      "c7500": "C7500",
      "caballero": "Caballero",
      "canyon": "Canyon",
      "denali": "Denali",
      "envoy": "Envoy",
      "forward control chassis": "Forward Control Chassis",
      "gmt-400": "GMT-400",
      "hummer ev": "Hummer EV",
      "hummer pickup": "Hummer Pickup",
      "hummer suv": "Hummer Suv",
      "jimmy": "Jimmy",
      "rally wagon / van": "Rally Wagon / Van",
      "s truck": "S Truck",
      "safari": "Safari",
      "savana": "Savana",
      "savana 1500": "Savana 1500",
      "savana 2500": "Savana 2500",
      "savana 3500": "Savana 3500",
      "savana 4500": "Savana 4500",
      "sierra": "Sierra",
      "sierra 1500": "Sierra 1500",
      "sierra 1500 limited": "Sierra 1500 Limited",
      "sierra 2500 hd": "Sierra 2500 HD",
      "sierra 3500 hd": "Sierra 3500 HD",
      "sonoma": "Sonoma",
      "sprint": "Sprint",
      "suburban": "Suburban",
      "t-series": "T-Series",
      "tc7500": "TC7500",
      "terrain": "Terrain",
      "topkick": "TopKick",
      "vandura": "Vandura",
      "w-series": "W-Series",
      "w3500": "W3500",
      "w4500": "W4500",
      "w4s042": "W4S042",
      "w5500": "W5500",
      "yukon": "Yukon",
      "yukon xl": "Yukon XL"
    }
  },
  "genesis": {
    "original": "Genesis",
    "models": {
      "g70": "G70",
      "g80": "G80",
      "g90": "G90",
      "gv60": "GV60",
      "gv70": "GV70",
      "gv80": "GV80"
    }
  },
  "geo": {
    "original": "Geo",
    "models": {
      "metro": "Metro",
      "prizm": "Prizm",
      "tracker": "Tracker"
    }
  },
  "glastron": {
    "original": "Glastron",
    "models": {
      "17 boat": "17 Boat",
      "boat": "Boat"
    }
  },
  "harley-davidson": {
    "original": "Harley-Davidson",
    "models": {
      "fl": "FL",
      "fld": "FLD",
      "flde": "FLDE",
      "flfb": "FLFB",
      "flfbs": "FLFBS",
      "flfbsanv": "FLFBSANV",
      "flhc": "FLHC",
      "flhcs": "FLHCS",
      "flhcsanv": "FLHCSANV",
      "flhp": "FLHP",
      "flhpi": "FLHPI",
      "flhr": "FLHR",
      "flhrc": "FLHRC",
      "flhrci": "FLHRCI",
      "flhri": "FLHRI",
      "flhrs": "FLHRS",
      "flhrse3": "FLHRSE3",
      "flhrse4": "FLHRSE4",
      "flhrsei1": "FLHRSEI1",
      "flhrsi": "FLHRSI",
      "flhrxs": "FLHRXS",
      "flhs": "FLHS",
      "flht": "FLHT",
      "flhtc": "FLHTC",
      "flhtci": "FLHTCI",
      "flhtcse": "FLHTCSE",
      "flhtcu": "FLHTCU",
      "flhtcui": "FLHTCUI",
      "flhtcul": "FLHTCUL",
      "flhtcuse": "FLHTCUSE",
      "flhtcuse6": "FLHTCUSE6",
      "flhtcuse7": "FLHTCUSE7",
      "flhtcutg": "FLHTCUTG",
      "flhti": "FLHTI",
      "flhtk": "FLHTK",
      "flhtkl": "FLHTKL",
      "flhtkse": "FLHTKSE",
      "flhtnse": "FLHTNSE",
      "flhtp": "FLHTP",
      "flhtpi": "FLHTPI",
      "flhx": "FLHX",
      "flhxi": "FLHXI",
      "flhxs": "FLHXS",
      "flhxsanv": "FLHXSANV",
      "flhxse": "FLHXSE",
      "flhxse2": "FLHXSE2",
      "flhxse3": "FLHXSE3",
      "flhxst": "FLHXST",
      "flhxu": "FLHXU",
      "flrt": "FLRT",
      "fls": "FLS",
      "flsb": "FLSB",
      "flsl": "FLSL",
      "flss": "FLSS",
      "flstc": "FLSTC",
      "flstci": "FLSTCI",
      "flstf": "FLSTF",
      "flstfb": "FLSTFB",
      "flstfbs": "FLSTFBS",
      "flstfi": "FLSTFI",
      "flstfse": "FLSTFSE",
      "flstn": "FLSTN",
      "flstni": "FLSTNI",
      "flsts": "FLSTS",
      "flstsb": "FLSTSB",
      "flstse": "FLSTSE",
      "flstsi": "FLSTSI",
      "fltc ultra": "FLTC ULTRA",
      "fltr": "FLTR",
      "fltri": "FLTRI",
      "fltrk": "FLTRK",
      "fltrkse": "FLTRKSE",
      "fltrse3": "FLTRSE3",
      "fltrsei": "FLTRSEI",
      "fltrt": "FLTRT",
      "fltru": "FLTRU",
      "fltruse": "FLTRUSE",
      "fltrx": "FLTRX",
      "fltrxp": "FLTRXP",
      "fltrxs": "FLTRXS",
      "fltrxsanv": "FLTRXSANV",
      "fltrxse": "FLTRXSE",
      "fltrxseanv": "FLTRXSEANV",
      "fltrxst": "FLTRXST",
      "fltrxstse": "FLTRXSTSE",
      "fxbb": "FXBB",
      "fxbbs": "FXBBS",
      "fxbr": "FXBR",
      "fxbrs": "FXBRS",
      "fxcw": "FXCW",
      "fxcwc": "FXCWC",
      "fxd": "FXD",
      "fxdb": "FXDB",
      "fxdbi": "FXDBI",
      "fxdbp dyna": "FXDBP DYNA",
      "fxdc": "FXDC",
      "fxdci": "FXDCI",
      "fxdf": "FXDF",
      "fxdi": "FXDI",
      "fxdl": "FXDL",
      "fxdli": "FXDLI",
      "fxdls": "FXDLS",
      "fxdrs": "FXDRS",
      "fxds": "FXDS",
      "fxdwg": "FXDWG",
      "fxdwgi": "FXDWGI",
      "fxdx": "FXDX",
      "fxdxt": "FXDXT",
      "fxfb": "FXFB",
      "fxfbs": "FXFBS",
      "fxlr": "FXLR",
      "fxlrs": "FXLRS",
      "fxlrst": "FXLRST",
      "fxrs": "FXRS",
      "fxrst": "FXRST",
      "fxrt": "FXRT",
      "fxs": "FXS",
      "fxsb": "FXSB",
      "fxsbse": "FXSBSE",
      "fxse": "FXSE",
      "fxst": "FXST",
      "fxstb": "FXSTB",
      "fxstbi": "FXSTBI",
      "fxstc": "FXSTC",
      "fxstd": "FXSTD",
      "fxstdi": "FXSTDI",
      "fxsti": "FXSTI",
      "fxsts": "FXSTS",
      "fxstsi": "FXSTSI",
      "fxstsse3": "FXSTSSE3",
      "ra1250": "RA1250",
      "rh1250 s": "RH1250 S",
      "rh975": "RH975",
      "road king": "Road King",
      "sportster 1200": "SPORTSTER 1200",
      "vrsca": "VRSCA",
      "vrscb": "VRSCB",
      "vrscd": "VRSCD",
      "vrscdx": "VRSCDX",
      "vrscf": "VRSCF",
      "vrscf vrod": "VRSCF VROD",
      "vrscse": "VRSCSE",
      "xg500": "XG500",
      "xg750": "XG750",
      "xl1200": "XL1200",
      "xl883": "XL883",
      "xlh": "XLH",
      "xlh1200": "XLH1200",
      "xlh883": "XLH883",
      "xr1200": "XR1200"
    }
  },
  "honda": {
    "original": "Honda",
    "models": {
      "adv150": "ADV150",
      "adv160": "ADV160",
      "accord": "Accord",
      "accord crosstour": "Accord Crosstour",
      "acty": "Acty",
      "aquatrax": "AquaTrax",
      "c125": "C125",
      "cb cycle": "CB CYCLE",
      "cb1000": "CB1000",
      "cb1100": "CB1100",
      "cb125": "CB125",
      "cb250": "CB250",
      "cb300": "CB300",
      "cb350": "CB350",
      "cb450": "CB450",
      "cb500": "CB500",
      "cb600": "CB600",
      "cb650": "CB650",
      "cb750": "CB750",
      "cb900": "CB900",
      "cbf300": "CBF300",
      "cbr cycle": "CBR CYCLE",
      "cbr1000": "CBR1000",
      "cbr1100": "CBR1100",
      "cbr1100xx": "CBR1100XX",
      "cbr125-r": "CBR125-R",
      "cbr250": "CBR250",
      "cbr300": "CBR300",
      "cbr500": "CBR500",
      "cbr600": "CBR600",
      "cbr600f": "CBR600F",
      "cbr650": "CBR650",
      "cbr900": "CBR900",
      "cbx250": "CBX250",
      "ch150": "CH150",
      "ch250": "CH250",
      "ch50": "CH50",
      "ch80": "CH80",
      "chf50": "CHF50",
      "cl350": "CL350",
      "cl500": "CL500",
      "cm cycle": "CM CYCLE",
      "cmx1100": "CMX1100",
      "cmx250": "CMX250",
      "cmx300": "CMX300",
      "cmx450": "CMX450",
      "cmx500": "CMX500",
      "cn250": "CN250",
      "cr-v": "CR-V",
      "cr-z": "CR-Z",
      "crf cycle": "CRF CYCLE",
      "crf1000": "CRF1000",
      "crf1100": "CRF1100",
      "crf150": "CRF150",
      "crf250": "CRF250",
      "crf300": "CRF300",
      "crf450": "CRF450",
      "ct125": "CT125",
      "ctx cycle": "CTX CYCLE",
      "ctx1300": "CTX1300",
      "ctx700": "CTX700",
      "cx500": "CX500",
      "civic": "Civic",
      "civic hybrid": "Civic Hybrid",
      "clarity": "Clarity",
      "clarity plug in hybrid": "Clarity Plug In Hybrid",
      "crosstour": "Crosstour",
      "cx500c": "Cx500c",
      "element": "Element",
      "fsc600": "FSC600",
      "fit": "Fit",
      "gl cycle": "GL CYCLE",
      "gl1100": "GL1100",
      "gl1200": "GL1200",
      "gl1500": "GL1500",
      "gl1800": "GL1800",
      "gl500": "GL500",
      "gold wing": "GOLD WING",
      "grom": "GROM",
      "hawk cb400": "HAWK CB400",
      "hr-v": "HR-V",
      "insight": "Insight",
      "mc": "MC",
      "nb50": "NB50",
      "nc cycle": "NC CYCLE",
      "nc700": "NC700",
      "nc750": "NC750",
      "nch50": "NCH50",
      "ncw50": "NCW50",
      "nhx110": "NHX110",
      "nps50": "NPS50",
      "nq50": "NQ50",
      "nsa700": "NSA700",
      "nss250": "NSS250",
      "nss300": "NSS300",
      "nt700": "NT700",
      "nva110": "NVA110",
      "odyssey": "Odyssey",
      "pc800": "PC800",
      "pcx": "PCX",
      "pcx150": "PCX150",
      "passport": "Passport",
      "pilot": "Pilot",
      "prelude": "Prelude",
      "prologue": "Prologue",
      "ruckus": "RUCKUS",
      "rvt1000": "RVT1000",
      "ridgeline": "Ridgeline",
      "s2000": "S2000",
      "sa50": "SA50",
      "sk50": "SK50",
      "spirit": "SPIRIT",
      "st cycle": "ST CYCLE",
      "st1100": "ST1100",
      "st1300": "ST1300",
      "sxs1000": "SXS1000",
      "sxs700": "SXS700",
      "side by side": "Side By Side",
      "trx": "TRX",
      "trx250": "TRX250",
      "trx350": "TRX350",
      "trx400": "TRX400",
      "trx420": "TRX420",
      "trx450": "TRX450",
      "trx500": "TRX500",
      "trx500fa": "TRX500FA",
      "trx520": "TRX520",
      "trx680": "TRX680",
      "trx90": "TRX90",
      "vf1100": "VF1100",
      "vf700": "VF700",
      "vf750": "VF750",
      "vfr cycle": "VFR CYCLE",
      "vfr1200": "VFR1200",
      "vfr700": "VFR700",
      "vfr750": "VFR750",
      "vfr800": "VFR800",
      "vt cycle": "VT CYCLE",
      "vt1100": "VT1100",
      "vt1300": "VT1300",
      "vt500": "VT500",
      "vt600": "VT600",
      "vt700": "VT700",
      "vt750": "VT750",
      "vtr1000": "VTR1000",
      "vtx cycle": "VTX CYCLE",
      "vtx1300": "VTX1300",
      "vtx1300c": "VTX1300C",
      "vtx1800": "VTX1800",
      "ww150": "WW150",
      "ww160 a": "WW160 A",
      "xl750": "XL750",
      "xr150l": "XR150L",
      "xr650": "XR650",
      "xr80": "XR80",
      "z125": "Z125"
    }
  },
  "hummer": {
    "original": "Hummer",
    "models": {
      "h1": "H1",
      "h2": "H2",
      "h3": "H3"
    }
  },
  "husqvarna": {
    "original": "Husqvarna",
    "models": {
      "701 enduro": "701 ENDURO",
      "fc450": "FC450",
      "fe350": "FE350",
      "fe501": "FE501",
      "fx350": "FX350",
      "norden 901": "NORDEN 901",
      "supermoto 701": "SUPERMOTO 701",
      "vitpilen": "VITPILEN",
      "vitpilen 401/svartpilen 401": "VITPILEN 401/SVARTPILEN 401"
    }
  },
  "hyosung": {
    "original": "Hyosung",
    "models": {
      "gt250": "GT250",
      "gv250": "GV250",
      "gv650": "GV650",
      "ms3-250": "MS3-250"
    }
  },
  "hyundai": {
    "original": "Hyundai",
    "models": {
      "53ft tralr": "53ft Tralr",
      "accent": "Accent",
      "azera": "Azera",
      "dry van": "Dry Van",
      "elantra": "Elantra",
      "elantra hybrid": "Elantra Hybrid",
      "elantra n": "Elantra N",
      "entourage": "Entourage",
      "equus": "Equus",
      "genesis": "Genesis",
      "grandeur": "Grandeur",
      "ioniq": "Ioniq",
      "ioniq 5": "Ioniq 5",
      "ioniq 6": "Ioniq 6",
      "ioniq hybrid": "Ioniq Hybrid",
      "kona": "Kona",
      "nexo": "NEXO",
      "palisade": "Palisade",
      "reefer": "Reefer",
      "santa cruz": "Santa Cruz",
      "santa fe": "Santa Fe",
      "santa fe hybrid": "Santa Fe Hybrid",
      "sonata": "Sonata",
      "sonata hybrid": "Sonata Hybrid",
      "tiburon": "Tiburon",
      "trailer": "Trailer",
      "translead": "Translead",
      "translead dry van trailer": "Translead Dry Van Trailer",
      "tucson": "Tucson",
      "tucson hybrid": "Tucson Hybrid",
      "van": "Van",
      "vc2530152-ajs dry van trailer": "Vc2530152-ajs Dry Van Trailer",
      "veloster": "Veloster",
      "venue": "Venue",
      "veracruz": "Veracruz",
      "xg": "XG"
    }
  },
  "ic corporation": {
    "original": "Ic Corporation",
    "models": {
      "3000": "3000",
      "3000 ce": "3000 Ce"
    }
  },
  "indian motorcycle co.": {
    "original": "Indian Motorcycle Co.",
    "models": {
      "chieftain": "CHIEFTAIN",
      "roadmaster": "ROADMASTER",
      "scout": "SCOUT",
      "springfield": "SPRINGFIELD"
    }
  },
  "infiniti": {
    "original": "Infiniti",
    "models": {
      "ex35": "EX35",
      "ex37": "EX37",
      "fx35": "FX35",
      "fx37": "FX37",
      "fx45": "FX45",
      "fx50": "FX50",
      "g20": "G20",
      "g25": "G25",
      "g35": "G35",
      "g37": "G37",
      "i30": "I30",
      "i35": "I35",
      "ipl g": "IPL G",
      "j30": "J30",
      "jx35": "JX35",
      "m30": "M30",
      "m35": "M35",
      "m35h": "M35h",
      "m37": "M37",
      "m45": "M45",
      "m56": "M56",
      "q40": "Q40",
      "q45": "Q45",
      "q50": "Q50",
      "q60": "Q60",
      "q70": "Q70",
      "qx30": "QX30",
      "qx4": "QX4",
      "qx50": "QX50",
      "qx55": "QX55",
      "qx56": "QX56",
      "qx60": "QX60",
      "qx70": "QX70",
      "qx80": "QX80"
    }
  },
  "international": {
    "original": "International",
    "models": {
      "2000": "2000",
      "3000 3800": "3000 3800",
      "4000-series": "4000-Series",
      "5000-series": "5000-Series",
      "7000-series": "7000-Series",
      "8000-series": "8000-Series",
      "9000-series": "9000-Series",
      "cv-series": "CV-Series",
      "durastar 4300": "Durastar 4300",
      "hv": "HV",
      "hx": "HX",
      "lt": "LT",
      "lonestar": "LoneStar",
      "mv-series": "MV-Series",
      "paystar": "PayStar",
      "prostar": "ProStar",
      "rh": "RH",
      "rh613": "Rh613",
      "s-series": "S-Series",
      "scout": "Scout",
      "terrastar": "TerraStar",
      "transtar": "Transtar",
      "travelall": "Travelall"
    }
  },
  "isuzu": {
    "original": "Isuzu",
    "models": {
      "amigo": "Amigo",
      "ascender": "Ascender",
      "axiom": "Axiom",
      "commercial van": "Commercial Van",
      "dsl reg": "Dsl Reg",
      "ftr": "FTR",
      "fvr": "FVR",
      "fxr": "FXR",
      "forward 1100": "Forward 1100",
      "forward 1400": "Forward 1400",
      "forward 800": "Forward 800",
      "hombre": "Hombre",
      "i-series": "I-Series",
      "npr": "NPR",
      "npr-hd": "NPR-HD",
      "npr-xd": "NPR-XD",
      "nqr": "NQR",
      "nrr": "NRR",
      "pup": "Pup",
      "reach": "Reach",
      "rodeo": "Rodeo",
      "trooper": "Trooper"
    }
  },
  "jaguar": {
    "original": "Jaguar",
    "models": {
      "e-pace": "E-Pace",
      "f-pace": "F-Pace",
      "f-type": "F-Type",
      "i-pace": "I-Pace",
      "s-type": "S-Type",
      "vandenplas": "Vandenplas",
      "x-type": "X-Type",
      "xe": "XE",
      "xf": "XF",
      "xj-series": "XJ-Series",
      "xk-series": "XK-Series"
    }
  },
  "jeep": {
    "original": "Jeep",
    "models": {
      "cj": "CJ",
      "cherokee": "Cherokee",
      "comanche": "Comanche",
      "commander": "Commander",
      "compass": "Compass",
      "dispatcher": "Dispatcher",
      "gladiator": "Gladiator",
      "grand cherokee": "Grand Cherokee",
      "grand cherokee l": "Grand Cherokee L",
      "grand cherokee wk": "Grand Cherokee WK",
      "grand wagoneer": "Grand Wagoneer",
      "j-series": "J-Series",
      "liberty": "Liberty",
      "patriot": "Patriot",
      "renegade": "Renegade",
      "scrambler": "Scrambler",
      "tj": "TJ",
      "wagoneer": "Wagoneer",
      "wrangler": "Wrangler",
      "wrangler unlimited": "Wrangler Unlimited"
    }
  },
  "kawasaki": {
    "original": "Kawasaki",
    "models": {
      "310": "310",
      "4010": "4010",
      "750ss": "750ss",
      "bn125": "BN125",
      "br125": "BR125",
      "cx500": "CX500",
      "ej800": "EJ800",
      "el450": "EL450",
      "en500": "EN500",
      "en650": "EN650",
      "er400 d": "ER400 D",
      "er500": "ER500",
      "er650": "ER650",
      "ex250": "EX250",
      "ex300": "EX300",
      "ex400": "EX400",
      "ex500": "EX500",
      "ex650": "EX650",
      "jh1200": "JH1200",
      "jt1100": "JT1100",
      "jt1500": "JT1500",
      "jet ski": "Jet Ski",
      "kaf": "KAF",
      "kaf1000": "KAF1000",
      "kaf400": "KAF400",
      "kaf620": "KAF620",
      "kaf820": "KAF820",
      "kat": "KAT",
      "kat820": "KAT820",
      "ke100-b": "KE100-B",
      "kl250": "KL250",
      "kl650": "KL650",
      "kle300": "KLE300",
      "kle650": "KLE650",
      "klf300": "KLF300",
      "klx110": "KLX110",
      "klx140": "KLX140",
      "klx230": "KLX230",
      "klx232": "KLX232",
      "klx250": "KLX250",
      "klx300": "KLX300",
      "klz1000 d": "KLZ1000 D",
      "krf": "KRF",
      "krf 1000": "KRF 1000",
      "krf800": "KRF800",
      "krt": "KRT",
      "krt750": "KRT750",
      "krt800": "KRT800",
      "krx": "KRX",
      "ksf50": "KSF50",
      "ksf90": "KSF90",
      "ksv": "KSV",
      "kvf300": "KVF300",
      "kvf450": "KVF450",
      "kvf650": "KVF650",
      "kvf750": "KVF750",
      "kwf1000": "KWF1000",
      "kwfridge": "KWFRidge",
      "kwt1000": "KWT1000",
      "kx250": "KX250",
      "kx252": "KX252",
      "kx450": "KX450",
      "kx85": "KX85",
      "kz1000": "KZ1000",
      "kz1100": "KZ1100",
      "kz440": "KZ440",
      "kz650": "KZ650",
      "le650": "LE650",
      "lz1000": "LZ1000",
      "marine/trl": "Marine/TRL",
      "mule": "Mule",
      "ninja": "NINJA",
      "ninja 250": "Ninja 250",
      "ninja 600": "Ninja 600",
      "stf-15": "STF-15",
      "stx160": "STX160",
      "sx-r": "SX-R",
      "side by side": "Side By Side",
      "teryx": "Teryx",
      "ultra": "Ultra",
      "ultra 250s": "Ultra 250s",
      "ultra 300x": "Ultra 300X",
      "vn1500": "VN1500",
      "vn1600": "VN1600",
      "vn1700": "VN1700",
      "vn2000": "VN2000",
      "vn750": "VN750",
      "vn800": "VN800",
      "vn800-b": "VN800-B",
      "vn900": "VN900",
      "vulcan": "Vulcan",
      "vulcan 2000": "Vulcan 2000",
      "zg1000": "ZG1000",
      "zg1200": "ZG1200",
      "zg1400": "ZG1400",
      "zr1000": "ZR1000",
      "zr1200 a": "ZR1200 A",
      "zr750": "ZR750",
      "zr800": "ZR800",
      "zr900": "ZR900",
      "zx1000": "ZX1000",
      "zx1002": "ZX1002",
      "zx1100": "ZX1100",
      "zx1200": "ZX1200",
      "zx1400": "ZX1400",
      "zx400": "ZX400",
      "zx600": "ZX600",
      "zx636": "ZX636",
      "zx750": "ZX750",
      "zx900": "ZX900",
      "zzr": "ZZR"
    }
  },
  "kia": {
    "original": "Kia",
    "models": {
      "amanti": "Amanti",
      "borrego": "Borrego",
      "cadenza": "Cadenza",
      "carnival": "Carnival",
      "ev6": "EV6",
      "ev9": "EV9",
      "forte": "Forte",
      "k4": "K4",
      "k5": "K5",
      "k900": "K900",
      "niro": "Niro",
      "optima": "Optima",
      "optima hybrid": "Optima Hybrid",
      "rio": "Rio",
      "rondo": "Rondo",
      "sedona": "Sedona",
      "seltos": "Seltos",
      "sephia": "Sephia",
      "sorento": "Sorento",
      "sorento hybrid": "Sorento Hybrid",
      "soul": "Soul",
      "spectra": "Spectra",
      "sportage": "Sportage",
      "sportage hybrid": "Sportage Hybrid",
      "stinger": "Stinger",
      "telluride": "Telluride"
    }
  },
  "ktm": {
    "original": "Ktm",
    "models": {
      "1090": "1090",
      "1190": "1190",
      "1290": "1290",
      "150": "150",
      "200": "200",
      "250": "250",
      "300": "300",
      "350": "350",
      "390": "390",
      "450": "450",
      "500": "500",
      "640": "640",
      "690": "690",
      "790": "790",
      "890": "890",
      "950": "950",
      "990": "990",
      "enduro": "ENDURO",
      "rc 390": "RC 390"
    }
  },
  "lamborghini": {
    "original": "Lamborghini",
    "models": {
      "aventador": "Aventador",
      "gallardo": "Gallardo",
      "huracan": "Huracan",
      "murcielago": "Murcielago",
      "urus": "Urus"
    }
  },
  "land rover": {
    "original": "Land Rover",
    "models": {
      "334": "334",
      "defender": "Defender",
      "discovery": "Discovery",
      "discovery sport": "Discovery Sport",
      "freelander": "Freelander",
      "lr2": "LR2",
      "lr3": "LR3",
      "lr4": "LR4",
      "range rover": "Range Rover",
      "range rover evoque": "Range Rover Evoque",
      "range rover sport": "Range Rover Sport",
      "range rover velar": "Range Rover Velar"
    }
  },
  "landau": {
    "original": "Landau",
    "models": {
      "other": "Other"
    }
  },
  "lexus": {
    "original": "Lexus",
    "models": {
      "ct": "CT",
      "ct 200": "CT 200",
      "ct 200h": "CT 200h",
      "es": "ES",
      "es 250": "ES 250",
      "es 300": "ES 300",
      "es 300h": "ES 300h",
      "es 330": "ES 330",
      "es 350": "ES 350",
      "gs": "GS",
      "gs 300": "GS 300",
      "gs 350": "GS 350",
      "gs 400": "GS 400",
      "gs 430": "GS 430",
      "gs 450": "GS 450",
      "gs 450h": "GS 450h",
      "gs 460": "GS 460",
      "gx": "GX",
      "gx 460": "GX 460",
      "gx 470": "GX 470",
      "gx 550": "GX 550",
      "hs": "HS",
      "hs 250h": "HS 250h",
      "is": "IS",
      "is 200t": "IS 200t",
      "is 250": "IS 250",
      "is 250c": "IS 250c",
      "is 300": "IS 300",
      "is 350": "IS 350",
      "is 350c": "IS 350c",
      "is 500": "IS 500",
      "is f": "IS F",
      "lc": "LC",
      "lc 500": "LC 500",
      "ls": "LS",
      "ls 400": "LS 400",
      "ls 430": "LS 430",
      "ls 460": "LS 460",
      "ls 500": "LS 500",
      "ls 500h": "LS 500h",
      "ls 600": "LS 600",
      "ls 600h": "LS 600h",
      "lx": "LX",
      "lx 450": "LX 450",
      "lx 470": "LX 470",
      "lx 570": "LX 570",
      "lx 600": "LX 600",
      "nx": "NX",
      "nx 200t": "NX 200t",
      "nx 250": "NX 250",
      "nx 300": "NX 300",
      "nx 300h": "NX 300h",
      "nx 350": "NX 350",
      "nx 350h": "NX 350h",
      "nx 450h+": "NX 450h+",
      "rc": "RC",
      "rc 200t": "RC 200t",
      "rc 300": "RC 300",
      "rc 350": "RC 350",
      "rc f": "RC F",
      "rx": "RX",
      "rx 300": "RX 300",
      "rx 330": "RX 330",
      "rx 350": "RX 350",
      "rx 350l": "RX 350L",
      "rx 350h": "RX 350h",
      "rx 400": "RX 400",
      "rx 400h": "RX 400h",
      "rx 450h": "RX 450h",
      "rx 450hl": "RX 450hL",
      "rx 500h": "RX 500h",
      "rz": "RZ",
      "rz 300e": "RZ 300e",
      "rz 450e": "RZ 450e",
      "sc": "SC",
      "sc 430": "SC 430",
      "sс 300": "SС 300",
      "sс 400": "SС 400",
      "tx": "TX",
      "tx 350": "TX 350",
      "tx 500h": "TX 500h",
      "ux": "UX",
      "ux 200": "UX 200",
      "ux 250h": "UX 250h",
      "ux 300h": "UX 300h"
    }
  },
  "lincoln": {
    "original": "Lincoln",
    "models": {
      "aviator": "Aviator",
      "blackwood": "Blackwood",
      "continental": "Continental",
      "corsair": "Corsair",
      "ls": "LS",
      "mkc": "MKC",
      "mks": "MKS",
      "mkt": "MKT",
      "mkx": "MKX",
      "mkz": "MKZ",
      "mark series": "Mark Series",
      "nautilus": "Nautilus",
      "navigator": "Navigator",
      "town car": "Town Car",
      "zephyr": "Zephyr"
    }
  },
  "lotus": {
    "original": "Lotus",
    "models": {
      "elise": "Elise",
      "emira": "Emira",
      "esprit": "Esprit",
      "evora": "Evora",
      "exige": "Exige"
    }
  },
  "lucid": {
    "original": "Lucid",
    "models": {
      "air": "Air"
    }
  },
  "malibu": {
    "original": "Malibu",
    "models": {
      "malibu": "Malibu",
      "other": "Other"
    }
  },
  "maserati": {
    "original": "Maserati",
    "models": {
      "coupe": "Coupe",
      "ghibli": "Ghibli",
      "granturismo": "GranTurismo",
      "grecale": "Grecale",
      "levante": "Levante",
      "mc20": "MC20",
      "quattroporte": "Quattroporte"
    }
  },
  "maybach": {
    "original": "Maybach",
    "models": {
      "57": "57",
      "62": "62"
    }
  },
  "mazda": {
    "original": "Mazda",
    "models": {
      "2": "2",
      "3": "3",
      "323": "323",
      "5": "5",
      "6": "6",
      "626": "626",
      "b2000": "B2000",
      "b2200": "B2200",
      "b2300": "B2300",
      "b2500": "B2500",
      "b2600": "B2600",
      "b3000": "B3000",
      "b4000": "B4000",
      "cx-3": "CX-3",
      "cx-30": "CX-30",
      "cx-5": "CX-5",
      "cx-50": "CX-50",
      "cx-7": "CX-7",
      "cx-70": "CX-70",
      "cx-9": "CX-9",
      "cx-90": "CX-90",
      "mpv": "MPV",
      "mx-3": "MX-3",
      "mx-30": "MX-30",
      "mx-5": "MX-5",
      "mx-5 miata": "MX-5 Miata",
      "mx-6": "MX-6",
      "millenia": "Millenia",
      "protege": "Protege",
      "rx-7": "RX-7",
      "rx-8": "RX-8",
      "tribute": "Tribute"
    }
  },
  "mclaren": {
    "original": "McLaren",
    "models": {
      "570gt": "570GT",
      "570s": "570S",
      "600lt": "600LT",
      "650s": "650S",
      "675lt": "675LT",
      "720s": "720S",
      "765lt": "765LT",
      "artura": "Artura",
      "gt": "GT",
      "mp4-12c": "MP4-12C"
    }
  },
  "mercedes-benz": {
    "original": "Mercedes-Benz",
    "models": {
      "190": "190",
      "200": "200",
      "230": "230",
      "240": "240",
      "260": "260",
      "280": "280",
      "300": "300",
      "380": "380",
      "400": "400",
      "420": "420",
      "500": "500",
      "560": "560",
      "a-class": "A-Class",
      "amg-class": "AMG-Class",
      "b-class": "B-Class",
      "c-class": "C-Class",
      "cl-class": "CL-Class",
      "cla-class": "CLA-Class",
      "cle-class": "CLE-Class",
      "clk-class": "CLK-Class",
      "cls-class": "CLS-Class",
      "e-class": "E-Class",
      "eqb": "EQB",
      "eqe": "EQE",
      "eqs": "EQS",
      "g-class": "G-Class",
      "gl-class": "GL-Class",
      "gla-class": "GLA-Class",
      "glb-class": "GLB-Class",
      "glc-class": "GLC-Class",
      "gle-class": "GLE-Class",
      "glk-class": "GLK-Class",
      "gls-class": "GLS-Class",
      "ml-class": "ML-Class",
      "maybach": "Maybach",
      "metris": "Metris",
      "r-class": "R-Class",
      "s-class": "S-Class",
      "sl-class": "SL-Class",
      "slc-class": "SLC-Class",
      "slk-class": "SLK-Class",
      "sls-class": "SLS-Class",
      "sprinter": "Sprinter"
    }
  },
  "mercury": {
    "original": "Mercury",
    "models": {
      "capri": "Capri",
      "comet": "Comet",
      "cougar": "Cougar",
      "grand marquis": "Grand Marquis",
      "marauder": "Marauder",
      "mariner": "Mariner",
      "milan": "Milan",
      "montclair": "Montclair",
      "montego": "Montego",
      "monterey": "Monterey",
      "mountaineer": "Mountaineer",
      "mystique": "Mystique",
      "sable": "Sable",
      "topaz": "Topaz",
      "tracer": "Tracer",
      "villager": "Villager"
    }
  },
  "mini": {
    "original": "Mini",
    "models": {
      "convertible": "Convertible",
      "cooper": "Cooper",
      "cooper clubman": "Cooper Clubman",
      "countryman": "Countryman",
      "coupe": "Coupe",
      "hardtop": "Hardtop",
      "john cooper works": "John Cooper Works",
      "paceman": "Paceman",
      "roadster": "Roadster"
    }
  },
  "mitsubishi": {
    "original": "Mitsubishi",
    "models": {
      "3000 gt": "3000 GT",
      "delica": "Delica",
      "diamante": "Diamante",
      "eclipse": "Eclipse",
      "endeavor": "Endeavor",
      "fuso": "Fuso",
      "galant": "Galant",
      "lancer": "Lancer",
      "lancer evolution": "Lancer Evolution",
      "miev": "Miev",
      "mighty max / s": "Mighty Max / S",
      "mirage": "Mirage",
      "montero": "Montero",
      "outlander": "Outlander",
      "outlander sport": "Outlander Sport",
      "rvr": "RVR",
      "raider": "Raider"
    }
  },
  "monark": {
    "original": "Monark",
    "models": {
      "other": "Other"
    }
  },
  "monterey": {
    "original": "Monterey",
    "models": {
      "boat": "Boat",
      "monterey": "Monterey"
    }
  },
  "moto guzzi": {
    "original": "Moto Guzzi",
    "models": {
      "norge": "NORGE",
      "stelvio": "STELVIO",
      "v11": "V11",
      "v7": "V7",
      "v85 tt": "V85 TT",
      "v9": "V9"
    }
  },
  "nissan": {
    "original": "Nissan",
    "models": {
      "200sx": "200SX",
      "240sx": "240SX",
      "300zx": "300ZX",
      "370z": "370Z",
      "4x2 truck": "4x2 Truck",
      "720": "720",
      "altima": "Altima",
      "altima hybrid": "Altima Hybrid",
      "ariya": "Ariya",
      "armada": "Armada",
      "cedric": "Cedric",
      "cube": "Cube",
      "d21": "D21",
      "elgrand": "Elgrand",
      "forklift": "Forklift",
      "frontier": "Frontier",
      "gt-r": "GT-R",
      "juke": "Juke",
      "kicks": "Kicks",
      "leaf": "Leaf",
      "maxima": "Maxima",
      "micra": "Micra",
      "murano": "Murano",
      "nv": "NV",
      "nv 1500": "NV 1500",
      "nv 200": "NV 200",
      "nv 2500": "NV 2500",
      "nv3500": "NV3500",
      "navara": "Navara",
      "pathfinder": "Pathfinder",
      "pulsar": "Pulsar",
      "qashqai": "Qashqai",
      "quest": "Quest",
      "rogue": "Rogue",
      "rogue sport": "Rogue Sport",
      "sentra": "Sentra",
      "stanza": "Stanza",
      "titan": "Titan",
      "truck": "Truck",
      "ud": "UD",
      "versa": "Versa",
      "versa note": "Versa Note",
      "x-trail": "X-Trail",
      "xterra": "Xterra",
      "z": "Z"
    }
  },
  "oday": {
    "original": "Oday",
    "models": {
      "boat": "Boat"
    }
  },
  "oldsmobile": {
    "original": "Oldsmobile",
    "models": {
      "88": "88",
      "98": "98",
      "alero": "Alero",
      "aurora": "Aurora",
      "bravada": "Bravada",
      "ciera": "Ciera",
      "cutlass": "Cutlass",
      "cutlass ciera": "Cutlass Ciera",
      "cutlass supreme": "Cutlass Supreme",
      "delta 88": "Delta 88",
      "intrigue": "Intrigue",
      "silhouette": "Silhouette"
    }
  },
  "piaggio": {
    "original": "Piaggio",
    "models": {
      "1 active": "1 ACTIVE",
      "bv": "BV",
      "fly": "FLY",
      "liberty": "LIBERTY",
      "lt": "LT",
      "mp3": "MP3",
      "typhoon": "TYPHOON",
      "vespa": "VESPA"
    }
  },
  "plymouth": {
    "original": "Plymouth",
    "models": {
      "acclaim": "Acclaim",
      "breeze": "Breeze",
      "grand voyager": "Grand Voyager",
      "neon": "Neon",
      "voyager": "Voyager"
    }
  },
  "polaris": {
    "original": "Polaris",
    "models": {
      "600": "600",
      "800": "800",
      "850": "850",
      "ace": "ACE",
      "all terrain pickup": "All Terrain Pickup",
      "general": "GENERAL",
      "hawkeye": "HAWKEYE",
      "indy": "Indy",
      "jet ski": "Jet Ski",
      "msx 140": "MSX 140",
      "outlaw": "OUTLAW",
      "pro xd": "PRO XD",
      "pro r600": "Pro R600",
      "proxd 4000 d": "Proxd 4000 D",
      "r": "R",
      "ranger": "Ranger",
      "rmk": "RMK",
      "rzr": "RZR",
      "rzr pro xp": "Rzr Pro Xp",
      "slingshot": "SLINGSHOT",
      "sportsman": "SPORTSMAN",
      "scrambler": "Scrambler",
      "side by side": "Side By Side",
      "snowmobile": "Snowmobile",
      "sportsman 570": "Sportsman 570",
      "switchback": "Switchback",
      "x2": "X2",
      "xpedition": "Xpedition"
    }
  },
  "polestar": {
    "original": "Polestar",
    "models": {
      "2": "2",
      "3": "3"
    }
  },
  "porsche": {
    "original": "Porsche",
    "models": {
      "718 boxster": "718 Boxster",
      "718 cayman": "718 Cayman",
      "911": "911",
      "914": "914",
      "924": "924",
      "928": "928",
      "944": "944",
      "968": "968",
      "boxster": "Boxster",
      "cayenne": "Cayenne",
      "cayman": "Cayman",
      "macan": "Macan",
      "panamera": "Panamera",
      "taycan": "Taycan"
    }
  },
  "premier": {
    "original": "Premier",
    "models": {
      "boat": "Boat",
      "other": "Other",
      "pontoon": "Pontoon"
    }
  },
  "pro-line": {
    "original": "Pro-Line",
    "models": {
      "other": "Other"
    }
  },
  "ram": {
    "original": "Ram",
    "models": {
      "1500": "1500",
      "2500": "2500",
      "3500": "3500",
      "4500": "4500",
      "5500": "5500",
      "dakota": "Dakota",
      "promaster 1500": "ProMaster 1500",
      "promaster 2500": "ProMaster 2500",
      "promaster 3500": "ProMaster 3500",
      "promaster city": "ProMaster City",
      "promaster": "Promaster",
      "promaster cargo van": "Promaster Cargo Van",
      "tradesman": "Tradesman",
      "trucks 1500": "Trucks 1500"
    }
  },
  "rivian": {
    "original": "Rivian",
    "models": {
      "edv": "Edv",
      "r1s": "R1S",
      "r1t": "R1T"
    }
  },
  "rolls-royce": {
    "original": "Rolls-Royce",
    "models": {
      "cullinan": "Cullinan",
      "dawn": "Dawn",
      "ghost": "Ghost",
      "phantom": "Phantom",
      "silver seraph": "Silver Seraph",
      "silver shadow": "Silver Shadow",
      "silver spirit": "Silver Spirit",
      "silver spur": "Silver Spur",
      "wraith": "Wraith"
    }
  },
  "saab": {
    "original": "Saab",
    "models": {
      "9-2": "9-2",
      "9-3": "9-3",
      "9-4": "9-4",
      "9-5": "9-5",
      "9-7x": "9-7X",
      "900": "900",
      "9000": "9000"
    }
  },
  "sail": {
    "original": "Sail",
    "models": {
      "boat": "Boat"
    }
  },
  "saturn": {
    "original": "Saturn",
    "models": {
      "astra": "Astra",
      "aura": "Aura",
      "ion": "Ion",
      "l-series": "L-Series",
      "l200": "L200",
      "l300": "L300",
      "outlook": "Outlook",
      "relay": "Relay",
      "s-series": "S-Series",
      "sc1": "Sc1",
      "sc2": "Sc2",
      "sky": "Sky",
      "sl": "Sl",
      "sl1": "Sl1",
      "sl2": "Sl2",
      "vue": "Vue"
    }
  },
  "scion": {
    "original": "Scion",
    "models": {
      "fr-s": "FR-S",
      "ia": "iA",
      "im": "iM",
      "iq": "iQ",
      "tc": "tC",
      "xa": "xA",
      "xb": "xB",
      "xd": "xD"
    }
  },
  "sea craft": {
    "original": "Sea Craft",
    "models": {
      "other": "Other"
    }
  },
  "sea ray": {
    "original": "Sea Ray",
    "models": {
      "200": "200",
      "boat": "Boat",
      "other": "Other",
      "sundance": "Sundance"
    }
  },
  "seaswirl": {
    "original": "Seaswirl",
    "models": {
      "other": "Other"
    }
  },
  "smart": {
    "original": "Smart",
    "models": {
      "fortwo": "Fortwo"
    }
  },
  "subaru": {
    "original": "Subaru",
    "models": {
      "ascent": "Ascent",
      "b9 tribeca": "B9 Tribeca",
      "brat": "BRAT",
      "brz": "BRZ",
      "baja": "Baja",
      "crosstrek": "Crosstrek",
      "forester": "Forester",
      "gl": "GL",
      "impreza": "Impreza",
      "justy": "Justy",
      "legacy": "Legacy",
      "loyale": "Loyale",
      "outback": "Outback",
      "svx": "SVX",
      "solterra": "Solterra",
      "tribeca": "Tribeca",
      "wrx": "WRX",
      "xv crosstrek": "XV Crosstrek"
    }
  },
  "suzuki": {
    "original": "Suzuki",
    "models": {
      "an400": "AN400",
      "an400 a": "AN400 A",
      "an650": "AN650",
      "atv": "ATV",
      "aerio": "Aerio",
      "boulevard": "BOULEVARD",
      "c50": "C50",
      "c90": "C90",
      "cyc vl/vlr": "CYC VL/VLR",
      "cyc vz/vzr": "CYC VZ/VZR",
      "cycle dl": "CYCLE DL",
      "cycle vs": "CYCLE VS",
      "carry": "Carry",
      "dirtbike": "DIRTBIKE",
      "dl1000": "DL1000",
      "dl1000 a": "DL1000 A",
      "dl1050": "DL1050",
      "dl1050 rc": "DL1050 RC",
      "dl650": "DL650",
      "dl650 a": "DL650 A",
      "dl800": "DL800",
      "dl800de rc": "DL800DE RC",
      "dr-z400": "DR-Z400",
      "dr-z400 s": "DR-Z400 S",
      "dr200": "DR200",
      "dr650": "DR650",
      "equator": "Equator",
      "esteem": "Esteem",
      "forenza": "Forenza",
      "gs1100": "GS1100",
      "gs450": "GS450",
      "gs500": "GS500",
      "gs750": "GS750",
      "gs850": "GS850",
      "gsf1200": "GSF1200",
      "gsf1250": "GSF1250",
      "gsf1250 sa": "GSF1250 SA",
      "gsf600": "GSF600",
      "gsx-r1000": "GSX-R1000",
      "gsx-r600": "GSX-R600",
      "gsx-r750": "GSX-R750",
      "gsx-r750 k": "GSX-R750 K",
      "gsx-s 1000sm": "GSX-S 1000SM",
      "gsx-s1000": "GSX-S1000",
      "gsx-s1000f": "GSX-S1000F",
      "gsx-s750": "GSX-S750",
      "gsx-s750 m": "GSX-S750 M",
      "gsx1000": "GSX1000",
      "gsx1000 gt": "GSX1000 GT",
      "gsx1100 f": "GSX1100 F",
      "gsx1250 f": "GSX1250 F",
      "gsx1300": "GSX1300",
      "gsx1300 r": "GSX1300 R",
      "gsx1300 rr": "GSX1300 RR",
      "gsx250": "GSX250",
      "gsx250r": "GSX250R",
      "gsx250r m": "GSX250R M",
      "gsx600": "GSX600",
      "gsx600f": "GSX600F",
      "gsx650": "GSX650",
      "gsx650 f": "GSX650 F",
      "gsx750": "GSX750",
      "gsx750 r": "GSX750 R",
      "gsx800": "GSX800",
      "gsx800 r": "GSX800 R",
      "gsxr1000": "GSXR1000",
      "gsxr600": "GSXR600",
      "gsxr750": "GSXR750",
      "gw250": "GW250",
      "gz250": "GZ250",
      "grand vitara": "Grand Vitara",
      "kizashi": "Kizashi",
      "ls650": "LS650",
      "lt": "LT",
      "lt-a750": "LT-A750",
      "m109r / vzr1800": "M109R / VZR1800",
      "m50": "M50",
      "r": "R",
      "rm-z250": "RM-Z250",
      "rm-z450": "RM-Z450",
      "rm125": "RM125",
      "rm250": "RM250",
      "sv1000": "SV1000",
      "sv650": "SV650",
      "sx4": "SX4",
      "samurai": "Samurai",
      "sidekick": "Sidekick",
      "swift": "Swift",
      "tl1000": "TL1000",
      "tu250": "TU250",
      "uh200": "UH200",
      "vl1500": "VL1500",
      "vl800": "VL800",
      "vl800 m": "VL800 M",
      "vlr1800": "VLR1800",
      "vs1400": "VS1400",
      "vs800": "VS800",
      "vz1500": "VZ1500",
      "vz1600": "VZ1600",
      "vz800": "VZ800",
      "vzr1800": "VZR1800",
      "vzr1800 z": "VZR1800 Z",
      "verona": "Verona",
      "xl-7": "XL-7"
    }
  },
  "sylvan": {
    "original": "Sylvan",
    "models": {
      "16\" boat/motor": "16\" Boat/motor",
      "pontoon": "Pontoon"
    }
  },
  "sym": {
    "original": "Sym",
    "models": {
      "cali class": "CALI CLASS",
      "fiddle ii": "FIDDLE II"
    }
  },
  "tesla": {
    "original": "Tesla",
    "models": {
      "cybertruck": "Cybertruck",
      "model 3": "Model 3",
      "model s": "Model S",
      "model x": "Model X",
      "model y": "Model Y",
      "roadster": "Roadster"
    }
  },
  "toyota": {
    "original": "Toyota",
    "models": {
      "4runner": "4Runner",
      "avalon": "Avalon",
      "avalon hybrid": "Avalon Hybrid",
      "bz4x": "BZ4X",
      "c-hr": "C-HR",
      "camry": "Camry",
      "camry hybrid": "Camry Hybrid",
      "celica": "Celica",
      "corolla": "Corolla",
      "corolla cross": "Corolla Cross",
      "cressida": "Cressida",
      "crown": "Crown",
      "echo": "Echo",
      "fj cruiser": "FJ Cruiser",
      "forklift": "Forklift",
      "gr 86": "GR 86",
      "gr corolla": "GR Corolla",
      "hiace": "Hiace",
      "highlander": "Highlander",
      "highlander hybrid": "Highlander Hybrid",
      "hilux": "Hilux",
      "land cruiser": "Land Cruiser",
      "matrix": "Matrix",
      "mirai": "Mirai",
      "mr2": "Mr2",
      "paseo": "Paseo",
      "pickup": "Pickup",
      "previa": "Previa",
      "prius": "Prius",
      "prius c": "Prius C",
      "prius plug-in": "Prius Plug-In",
      "prius prime": "Prius Prime",
      "prius v": "Prius V",
      "rav4": "RAV4",
      "rav4 hybrid": "RAV4 Hybrid",
      "rav4 prime": "RAV4 Prime",
      "scion": "SCION",
      "scion fr-s": "SCION FR-S",
      "sequoia": "Sequoia",
      "sienna": "Sienna",
      "supra": "Supra",
      "t100": "T100",
      "tacoma": "Tacoma",
      "tercel": "Tercel",
      "tundra": "Tundra",
      "van wagon": "Van Wagon",
      "venza": "Venza",
      "yaris": "Yaris"
    }
  },
  "tracker": {
    "original": "Tracker",
    "models": {
      "bass tracker": "Bass Tracker",
      "other": "Other"
    }
  },
  "triumph motorcycle": {
    "original": "Triumph Motorcycle",
    "models": {
      "bonneville": "BONNEVILLE",
      "thunderbird": "THUNDERBIRD",
      "tiger": "TIGER"
    }
  },
  "vespa": {
    "original": "Vespa",
    "models": {
      "150": "150",
      "50": "50",
      "c161c": "C161C",
      "granturismo": "GRANTURISMO",
      "gts": "GTS",
      "gts 300": "GTS 300",
      "gts/sei giorni": "GTS/SEI GIORNI",
      "lx": "LX",
      "m198f": "M198F",
      "primavera/sprint": "PRIMAVERA/SPRINT",
      "sprint": "SPRINT"
    }
  },
  "victory motorcycles": {
    "original": "Victory Motorcycles",
    "models": {
      "cross country": "CROSS COUNTRY",
      "magnum": "MAGNUM"
    }
  },
  "volkswagen": {
    "original": "Volkswagen",
    "models": {
      "arteon": "Arteon",
      "atlas": "Atlas",
      "atlas cross sport": "Atlas Cross Sport",
      "beetle": "Beetle",
      "cc": "CC",
      "cabrio": "Cabrio",
      "cabriolet": "Cabriolet",
      "city golf": "City Golf",
      "eos": "Eos",
      "eurovan": "Eurovan",
      "gli": "GLI",
      "gti": "GTI",
      "golf": "Golf",
      "golf alltrack": "Golf Alltrack",
      "golf r": "Golf R",
      "golf sportwagen": "Golf SportWagen",
      "id. buzz": "ID. Buzz",
      "id.4": "ID.4",
      "jetta": "Jetta",
      "minivan": "Minivan",
      "passat": "Passat",
      "r32": "R32",
      "rabbit": "Rabbit",
      "routan": "Routan",
      "taos": "Taos",
      "tiguan": "Tiguan",
      "tiguan limited": "Tiguan Limited",
      "touareg": "Touareg",
      "transporter": "Transporter",
      "vanagon": "Vanagon",
      "vento": "Vento",
      "e-golf": "e-Golf"
    }
  },
  "volvo": {
    "original": "Volvo",
    "models": {
      "240": "240",
      "740": "740",
      "850": "850",
      "940": "940",
      "960": "960",
      "acl": "ACL",
      "aero": "Aero",
      "c30": "C30",
      "c40": "C40",
      "c70": "C70",
      "conventional": "Conventional",
      "ex30": "EX30",
      "fe": "FE",
      "p1800s": "P1800s",
      "s40": "S40",
      "s60": "S60",
      "s60 cross country": "S60 Cross Country",
      "s70": "S70",
      "s80": "S80",
      "s90": "S90",
      "v40": "V40",
      "v50": "V50",
      "v60": "V60",
      "v60 cross country": "V60 Cross Country",
      "v70": "V70",
      "v90": "V90",
      "v90 cross country": "V90 Cross Country",
      "vah": "VAH",
      "vhd": "VHD",
      "vn": "VN",
      "vnl": "VNL",
      "vnl 300": "VNL 300",
      "vnl 430": "VNL 430",
      "vnl 630": "VNL 630",
      "vnl 670": "VNL 670",
      "vnl 740": "VNL 740",
      "vnl 760": "VNL 760",
      "vnl 860": "VNL 860",
      "vnm": "VNM",
      "vnr": "VNR",
      "wg": "WG",
      "xc": "XC",
      "xc40": "XC40",
      "xc40 recharge": "XC40 Recharge",
      "xc60": "XC60",
      "xc60 recharge": "XC60 Recharge",
      "xc70": "XC70",
      "xc90": "XC90",
      "xc90 recharge": "XC90 Recharge",
      "xpeditor": "Xpeditor"
    }
  },
  "yamaha": {
    "original": "Yamaha",
    "models": {
      "boat": "Boat",
      "cp250": "CP250",
      "cw50": "CW50",
      "cx50 u": "CX50 U",
      "czd300 a": "CZD300 A",
      "cruiser": "Cruiser",
      "ex": "EX",
      "ex sport": "EX Sport",
      "fj09": "FJ09",
      "fj1200": "FJ1200",
      "fjr1300": "FJR1300",
      "fx": "FX",
      "fx ho": "FX HO",
      "fx-1": "FX-1",
      "fz07": "FZ07",
      "fz07a": "FZ07A",
      "fz09": "FZ09",
      "fz1": "FZ1",
      "fz10": "FZ10",
      "fz6": "FZ6",
      "fz8": "FZ8",
      "fzs10": "FZS10",
      "gp1800": "GP1800",
      "gp1800r": "GP1800R",
      "gx1800": "GX1800",
      "grizzly": "Grizzly",
      "jet ski": "Jet ski",
      "jetblaster": "JetBlaster",
      "mt-03": "MT-03",
      "mt-07": "MT-07",
      "mt07": "MT07",
      "mt09": "MT09",
      "mt10": "MT10",
      "mtm690": "MTM690",
      "mtm890": "MTM890",
      "mtn1000": "MTN1000",
      "mtn320": "MTN320",
      "mtn690": "MTN690",
      "mtt09": "MTT09",
      "mxt850 gt": "MXT850 GT",
      "pw50": "PW50",
      "scr950": "SCR950",
      "sr400": "SR400",
      "sr500": "SR500",
      "srviper": "SRViper",
      "sidewinder": "Sidewinder",
      "snowmobile": "Snowmobile",
      "ttr125": "TTR125",
      "tw200": "TW200",
      "v1 sport": "V1 Sport",
      "vino": "VINO",
      "vino yj50r": "VINO YJ50R",
      "vmx12": "VMX12",
      "vp11": "VP11",
      "vx": "VX",
      "vx cruiser": "VX Cruiser",
      "vx deluxe": "VX Deluxe",
      "vx1050fr": "VX1050FR",
      "wr250": "WR250",
      "wr450": "WR450",
      "waveraider": "Waveraider",
      "waverunner": "Waverunner",
      "xc125": "XC125",
      "xc155": "XC155",
      "xc50": "XC50",
      "xf50": "XF50",
      "xj600": "XJ600",
      "xj700": "XJ700",
      "xj750": "XJ750",
      "xl 1200": "XL 1200",
      "xp500": "XP500",
      "xs1100": "XS1100",
      "xsr700": "XSR700",
      "xsr900": "XSR900",
      "xt1200z": "XT1200Z",
      "xt1200ze": "XT1200ZE",
      "xt225": "XT225",
      "xt250": "XT250",
      "xtz690": "XTZ690",
      "xv1000": "XV1000",
      "xv1100": "XV1100",
      "xv1600": "XV1600",
      "xv1700": "XV1700",
      "xv1900": "XV1900",
      "xv250": "XV250",
      "xv500": "XV500",
      "xv535": "XV535",
      "xv750": "XV750",
      "xv920": "XV920",
      "xvs1100": "XVS1100",
      "xvs1300": "XVS1300",
      "xvs1300 a": "XVS1300 A",
      "xvs65": "XVS65",
      "xvs650": "XVS650",
      "xvs950": "XVS950",
      "xvs950 cr": "XVS950 CR",
      "xvs950cu": "XVS950CU",
      "xvz12": "XVZ12",
      "xvz13": "XVZ13",
      "xvz13 tf": "XVZ13 TF",
      "yfm": "YFM",
      "yfm250": "YFM250",
      "yfm350": "YFM350",
      "yfm450": "YFM450",
      "yfm550": "YFM550",
      "yfm700": "YFM700",
      "yfz320": "YFZ320",
      "yfz450": "YFZ450",
      "yj125": "YJ125",
      "yj50": "YJ50",
      "yw125": "YW125",
      "yw50": "YW50",
      "yx": "YX",
      "yxe850": "YXE850",
      "yxm700": "YXM700",
      "yxr700": "YXR700",
      "yxz1000": "YXZ1000",
      "yz125": "YZ125",
      "yz250": "YZ250",
      "yz450": "YZ450",
      "yzf1000": "YZF1000",
      "yzf600": "YZF600",
      "yzf890": "YZF890",
      "yzfr1": "YZFR1",
      "yzfr1m": "YZFR1M",
      "yzfr1s": "YZFR1S",
      "yzfr3": "YZFR3",
      "yzfr6": "YZFR6",
      "yzfr7": "YZFR7"
    }
  }
}