"""temp_migration

Revision ID: 1185cc831b93
Revises: edd45a9efaa6
Create Date: 2025-05-15 11:17:43.767029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1185cc831b93"
down_revision: Union[str, None] = "edd45a9efaa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roi", "roi", existing_type=sa.INTEGER(), type_=sa.Float(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("roi", "roi", existing_type=sa.Float(), type_=sa.INTEGER(), existing_nullable=False)
    # ### end Alembic commands ###
