"""initial migration

Revision ID: 1f430822b583
Revises: 
Create Date: 2025-06-25 10:17:06.384282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f430822b583"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vin", sa.String(), nullable=False),
        sa.Column("vehicle", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("make", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("mileage", sa.Integer(), nullable=True),
        sa.Column("auction", sa.String(), nullable=True),
        sa.Column("auction_name", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("lot", sa.Integer(), nullable=True),
        sa.Column("seller", sa.String(), nullable=True),
        sa.Column("owners", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("accident_count", sa.Integer(), nullable=True),
        sa.Column("has_correct_vin", sa.Boolean(), nullable=False),
        sa.Column("has_correct_owners", sa.Boolean(), nullable=False),
        sa.Column("has_correct_accidents", sa.Boolean(), nullable=False),
        sa.Column("has_correct_mileage", sa.Boolean(), nullable=False),
        sa.Column("current_bid", sa.Float(), nullable=True),
        sa.Column("actual_bid", sa.Float(), nullable=True),
        sa.Column("price_sold", sa.Float(), nullable=True),
        sa.Column("suggested_bid", sa.Float(), nullable=True),
        sa.Column("avg_market_price", sa.Integer(), nullable=True),
        sa.Column("parts_cost", sa.Float(), nullable=True),
        sa.Column("maintenance", sa.Float(), nullable=True),
        sa.Column("auction_fee", sa.Float(), nullable=True),
        sa.Column("transportation", sa.Float(), nullable=True),
        sa.Column("labor", sa.Float(), nullable=True),
        sa.Column("is_salvage", sa.Boolean(), nullable=True),
        sa.Column("parts_needed", sa.String(), nullable=True),
        sa.Column(
            "recommendation_status",
            sa.Enum("RECOMMENDED", "NOT_RECOMMENDED", name="recommendationstatus"),
            nullable=False,
        ),
        sa.Column(
            "car_status",
            sa.Enum("NEW", "TO_BID", "BIDDING", "WON", "FAILED", "DELETED_FROM_BIDDING_HUB", name="carstatus"),
            nullable=False,
        ),
        sa.Column("engine", sa.Float(), nullable=True),
        sa.Column("has_keys", sa.Boolean(), nullable=True),
        sa.Column("predicted_roi", sa.Float(), nullable=True),
        sa.Column("predicted_profit_margin", sa.Float(), nullable=True),
        sa.Column("predicted_profit_margin_percent", sa.Float(), nullable=True),
        sa.Column("predicted_total_investments", sa.Float(), nullable=True),
        sa.Column("engine_cylinder", sa.Integer(), nullable=True),
        sa.Column("drive_type", sa.String(), nullable=True),
        sa.Column("interior_color", sa.String(), nullable=True),
        sa.Column("exterior_color", sa.String(), nullable=True),
        sa.Column("body_style", sa.String(), nullable=True),
        sa.Column("style_id", sa.Integer(), nullable=True),
        sa.Column("transmision", sa.String(), nullable=True),
        sa.Column("vehicle_type", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vin"),
    )
    op.create_index(op.f("ix_cars_id"), "cars", ["id"], unique=False)
    op.create_index(op.f("ix_cars_mileage"), "cars", ["mileage"], unique=False)
    op.create_table(
        "fees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction", sa.String(), nullable=False),
        sa.Column("fee_type", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("percent", sa.Boolean(), nullable=False),
        sa.Column("price_from", sa.Float(), nullable=True),
        sa.Column("price_to", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fees_id"), "fees", ["id"], unique=False)
    op.create_table(
        "filters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("make", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("year_from", sa.Integer(), nullable=True),
        sa.Column("year_to", sa.Integer(), nullable=True),
        sa.Column("odometer_min", sa.Integer(), nullable=True),
        sa.Column("odometer_max", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_filters_id"), "filters", ["id"], unique=False)
    op.create_table(
        "part_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vehicle", sa.String(), nullable=False),
        sa.Column("part_description", sa.String(), nullable=False),
        sa.Column("supplier", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column(
            "part_status",
            sa.Enum(
                "PENDING_TO_ORDER",
                "ORDERED",
                "PENDING_TO_ARRIVED",
                "PAID",
                "CANCELLED",
                "RECEIVED",
                "PENDING_FOR_RETURN",
                "SWAP",
                "RETURNED",
                "CANT_RETURN",
                "REFUND_REQUEST",
                "REFUNDED",
                name="partinventorystatus",
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_part_inventory_id"), "part_inventory", ["id"], unique=False)
    op.create_table(
        "roi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("roi", sa.Float(), nullable=False),
        sa.Column("profit_margin", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roi_id"), "roi", ["id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.Enum("USER", "VEHICLE_MANAGER", "PART_MANAGER", "ADMIN", name="userroleenum"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "auto_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.Column("screenshot_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auto_checks_id"), "auto_checks", ["id"], unique=False)
    op.create_table(
        "car_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.DateTime(), nullable=False),
        sa.Column("vehicle", sa.String(), nullable=False),
        sa.Column("vin", sa.String(), nullable=False),
        sa.Column("stock", sa.String(), nullable=False),
        sa.Column("net_profit", sa.Float(), nullable=True),
        sa.Column("vehicle_cost", sa.Float(), nullable=True),
        sa.Column("parts_cost", sa.Float(), nullable=True),
        sa.Column("maintenance", sa.Float(), nullable=True),
        sa.Column("auction_fee", sa.Float(), nullable=True),
        sa.Column("transportation", sa.Float(), nullable=True),
        sa.Column("labor", sa.Float(), nullable=True),
        sa.Column("additional_costs", sa.Float(), nullable=True),
        sa.Column(
            "car_status",
            sa.Enum(
                "AWAITING_DELIVERY",
                "IN_INVENTORY",
                "UNDER_REPAIR",
                "LISTED_OFR_SALE",
                "ACTIVE_SALE",
                "SOLD",
                name="carinventorystatus",
            ),
            nullable=False,
        ),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_inventory_id"), "car_inventory", ["id"], unique=False)
    op.create_table(
        "car_sale_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("lot_number", sa.Integer(), nullable=True),
        sa.Column("final_bid", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_sale_history_id"), "car_sale_history", ["id"], unique=False)
    op.create_table(
        "condition_assessments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("type_of_damage", sa.String(), nullable=True),
        sa.Column("issue_description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_condition_assessments_id"), "condition_assessments", ["id"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("part_inventory_id", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["part_inventory_id"], ["part_inventory.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invoices_id"), "invoices", ["id"], unique=False)
    op.create_table(
        "parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_parts_id"), "parts", ["id"], unique=False)
    op.create_table(
        "photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("is_hd", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_photos_id"), "photos", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("temp_email", sa.String(), nullable=True),
        sa.Column("_hashed_password", sa.String(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["user_roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "car_inventory_investments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column(
            "investment_type",
            sa.Enum(
                "AUCTION_FEE",
                "TRANSPORTATION",
                "PARTS",
                "MAINTENANCE",
                "ADDITIONAL_COSTS",
                "LABOR",
                name="carinventoryinvestmentstype",
            ),
            nullable=False,
        ),
        sa.Column("car_inventory_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["car_inventory_id"], ["car_inventory.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_inventory_investments_id"), "car_inventory_investments", ["id"], unique=False)
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("car_inventory_id", sa.Integer(), nullable=True),
        sa.Column("part_inventory_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["cars.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["car_inventory_id"], ["car_inventory.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["part_inventory_id"], ["part_inventory.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_history_id"), "history", ["id"], unique=False)
    op.create_table(
        "user_likes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["car_id"],
            ["cars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "car_id"),
    )
    op.create_index("ix_user_car", "user_likes", ["user_id", "car_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_car", table_name="user_likes")
    op.drop_table("user_likes")
    op.drop_index(op.f("ix_history_id"), table_name="history")
    op.drop_table("history")
    op.drop_index(op.f("ix_car_inventory_investments_id"), table_name="car_inventory_investments")
    op.drop_table("car_inventory_investments")
    op.drop_table("users")
    op.drop_index(op.f("ix_photos_id"), table_name="photos")
    op.drop_table("photos")
    op.drop_index(op.f("ix_parts_id"), table_name="parts")
    op.drop_table("parts")
    op.drop_index(op.f("ix_invoices_id"), table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_condition_assessments_id"), table_name="condition_assessments")
    op.drop_table("condition_assessments")
    op.drop_index(op.f("ix_car_sale_history_id"), table_name="car_sale_history")
    op.drop_table("car_sale_history")
    op.drop_index(op.f("ix_car_inventory_id"), table_name="car_inventory")
    op.drop_table("car_inventory")
    op.drop_index(op.f("ix_auto_checks_id"), table_name="auto_checks")
    op.drop_table("auto_checks")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_roi_id"), table_name="roi")
    op.drop_table("roi")
    op.drop_index(op.f("ix_part_inventory_id"), table_name="part_inventory")
    op.drop_table("part_inventory")
    op.drop_index(op.f("ix_filters_id"), table_name="filters")
    op.drop_table("filters")
    op.drop_index(op.f("ix_fees_id"), table_name="fees")
    op.drop_table("fees")
    op.drop_index(op.f("ix_cars_mileage"), table_name="cars")
    op.drop_index(op.f("ix_cars_id"), table_name="cars")
    op.drop_table("cars")
    # ### end Alembic commands ###
