"""temp_migration

Revision ID: 3103b8be0e0d
Revises: 4b0b851ffcb2
Create Date: 2025-12-22 12:00:41.734666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3103b8be0e0d'
down_revision: Union[str, None] = '4b0b851ffcb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('is_manually_upserted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'is_manually_upserted')
    # ### end Alembic commands ###
