"""temp_migration

Revision ID: 56c83322b8de
Revises: a070b32efb0a
Create Date: 2025-05-20 09:12:13.776386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "56c83322b8de"
down_revision: Union[str, None] = "a070b32efb0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("car_inventory", sa.Column("car_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "car_inventory", "cars", ["car_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "car_inventory", type_="foreignkey")
    op.drop_column("car_inventory", "car_id")
    # ### end Alembic commands ###
