"""temp_migration

Revision ID: 665eee3c371d
Revises: 0b0b4deacf7f
Create Date: 2025-05-20 11:54:14.368510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "665eee3c371d"
down_revision: Union[str, None] = "0b0b4deacf7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("history_car_inventory_id_fkey", "history", type_="foreignkey")
    op.create_foreign_key(None, "history", "car_inventory", ["car_inventory_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "history", type_="foreignkey")
    op.create_foreign_key(
        "history_car_inventory_id_fkey", "history", "cars", ["car_inventory_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
