"""temp_migration

Revision ID: 8eb3a7817397
Revises: 8384d44c32b5
Create Date: 2025-04-30 08:14:43.195795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eb3a7817397'
down_revision: Union[str, None] = '8384d44c32b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bidding_hub_history', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('bidding_hub_history', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('bidding_hub_history', 'date')
    op.add_column('cars', sa.Column('current_bid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'current_bid')
    op.add_column('bidding_hub_history', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('bidding_hub_history', 'comment')
    op.drop_column('bidding_hub_history', 'created_at')
    # ### end Alembic commands ###
