"""temp_migration

Revision ID: a070b32efb0a
Revises: 1185cc831b93
Create Date: 2025-05-20 09:07:05.663928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a070b32efb0a"
down_revision: Union[str, None] = "1185cc831b93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "car_inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.DateTime(), nullable=False),
        sa.Column("vehicle", sa.String(), nullable=False),
        sa.Column("vin", sa.String(), nullable=False),
        sa.Column("stock", sa.String(), nullable=False),
        sa.Column("net_profit", sa.Float(), nullable=True),
        sa.Column("vehicle_cost", sa.Float(), nullable=False),
        sa.Column("parts_cost", sa.Float(), nullable=True),
        sa.Column("maintenance", sa.Float(), nullable=True),
        sa.Column("auction_fee", sa.Float(), nullable=True),
        sa.Column("transportation", sa.Float(), nullable=True),
        sa.Column("labor", sa.Float(), nullable=True),
        sa.Column("additional_costs", sa.Float(), nullable=True),
        sa.Column(
            "car_status",
            sa.Enum(
                "AWAITING_DELIVERY",
                "IN_INVENTORY",
                "UNDER_REPAIR",
                "LISTED_OFR_SALE",
                "ACTIVE_SALE",
                "SOLD",
                name="carinventorystatus",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_inventory_id"), "car_inventory", ["id"], unique=False)
    op.create_table(
        "car_inventory_investments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column(
            "investment_type",
            sa.Enum(
                "AUCTION_FEE",
                "TRANSPORTATION",
                "PARTS",
                "MAINTENANCE",
                "ADDITIONAL_COSTS",
                "LABOR",
                name="carinventoryinvestmentstype",
            ),
            nullable=False,
        ),
        sa.Column("car_inventory_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["car_inventory_id"], ["car_inventory.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_car_inventory_investments_id"), "car_inventory_investments", ["id"], unique=False)
    op.create_table(
        "inventory_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("car_inventory_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["car_inventory_id"], ["car_inventory.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_inventory_history_id"), "inventory_history", ["id"], unique=False)
    op.add_column("cars", sa.Column("predicted_profit_margin_percent", sa.Float(), nullable=True))
    op.add_column("cars", sa.Column("predicted_total_investments", sa.Float(), nullable=True))
    op.drop_column("cars", "roi")
    op.drop_column("cars", "net_profit")
    op.drop_column("cars", "bid")
    op.drop_column("cars", "total_investment")
    op.drop_column("cars", "profit_margin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cars", sa.Column("profit_margin", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("cars", sa.Column("total_investment", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column("cars", sa.Column("bid", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column(
        "cars", sa.Column("net_profit", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.add_column("cars", sa.Column("roi", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column("cars", "predicted_total_investments")
    op.drop_column("cars", "predicted_profit_margin_percent")
    op.drop_index(op.f("ix_inventory_history_id"), table_name="inventory_history")
    op.drop_table("inventory_history")
    op.drop_index(op.f("ix_car_inventory_investments_id"), table_name="car_inventory_investments")
    op.drop_table("car_inventory_investments")
    op.drop_index(op.f("ix_car_inventory_id"), table_name="car_inventory")
    op.drop_table("car_inventory")
    # ### end Alembic commands ###
