"""temp_migration

Revision ID: a159dc37be04
Revises: c6aaa73d10fb
Create Date: 2025-06-13 10:16:34.130521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a159dc37be04'
down_revision: Union[str, None] = 'c6aaa73d10fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('part_inventory', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('part_inventory', 'comment')
    # ### end Alembic commands ###
