"""temp_migration

Revision ID: ca4113184633
Revises: 3103b8be0e0d
Create Date: 2026-04-16 09:50:21.055806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca4113184633'
down_revision: Union[str, None] = '3103b8be0e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_kickoff_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filter_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DISPATCHED', 'DONE', 'FAILED', name='filter_kickoff_queue_status'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filter_id'], ['filters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_kickoff_queue_celery_task_id'), 'filter_kickoff_queue', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_filter_kickoff_queue_filter_id'), 'filter_kickoff_queue', ['filter_id'], unique=True)
    op.create_index(op.f('ix_filter_kickoff_queue_scheduled_at'), 'filter_kickoff_queue', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_filter_kickoff_queue_status'), 'filter_kickoff_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filter_kickoff_queue_status'), table_name='filter_kickoff_queue')
    op.drop_index(op.f('ix_filter_kickoff_queue_scheduled_at'), table_name='filter_kickoff_queue')
    op.drop_index(op.f('ix_filter_kickoff_queue_filter_id'), table_name='filter_kickoff_queue')
    op.drop_index(op.f('ix_filter_kickoff_queue_celery_task_id'), table_name='filter_kickoff_queue')
    op.drop_table('filter_kickoff_queue')
    # ### end Alembic commands ###
