"""temp_migration

Revision ID: dfd58ec5d170
Revises: e32c313baf1b
Create Date: 2025-06-13 11:43:34.448262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfd58ec5d170'
down_revision: Union[str, None] = 'e32c313baf1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_sale_history', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('car_sale_history', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('car_sale_history', 'lot_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_sale_history', 'lot_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('car_sale_history', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('car_sale_history', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
