"""temp_migration

Revision ID: e32c313baf1b
Revises: 665eee3c371d
Create Date: 2025-06-04 12:08:06.267750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32c313baf1b'
down_revision: Union[str, None] = '665eee3c371d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction', sa.String(), nullable=False),
    sa.Column('fee_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price_from', sa.Float(), nullable=True),
    sa.Column('price_to', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fees_id'), 'fees', ['id'], unique=False)
    op.create_table('part_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('part_description', sa.String(), nullable=False),
    sa.Column('supplier', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('part_status', sa.Enum('PENDING_TO_ORDER', 'ORDERED', 'PENDING_TO_ARRIVED', 'PAID', 'CANCELLED', 'RECEIVED', 'PENDING_FOR_RETURN', 'SWAP', 'RETURNED', 'CANT_RETURN', 'REFUND_REQUEST', 'REFUNDED', name='partinventorystatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_part_inventory_id'), 'part_inventory', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_inventory_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['part_inventory_id'], ['part_inventory.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.add_column('history', sa.Column('part_inventory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'history', 'part_inventory', ['part_inventory_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'part_inventory_id')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_part_inventory_id'), table_name='part_inventory')
    op.drop_table('part_inventory')
    op.drop_index(op.f('ix_fees_id'), table_name='fees')
    op.drop_table('fees')
    # ### end Alembic commands ###
