"""temp_migration

Revision ID: ea3b020055e5
Revises: 941ecc6a249c
Create Date: 2025-08-18 09:15:48.282233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3b020055e5'
down_revision: Union[str, None] = '941ecc6a249c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auto_checks_car_id'), 'auto_checks', ['car_id'], unique=False)
    op.create_index(op.f('ix_car_sale_history_car_id'), 'car_sale_history', ['car_id'], unique=False)
    op.create_index(op.f('ix_condition_assessments_car_id'), 'condition_assessments', ['car_id'], unique=False)
    op.create_index(op.f('ix_parts_car_id'), 'parts', ['car_id'], unique=False)
    op.create_index(op.f('ix_photos_car_id'), 'photos', ['car_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_car_id'), table_name='photos')
    op.drop_index(op.f('ix_parts_car_id'), table_name='parts')
    op.drop_index(op.f('ix_condition_assessments_car_id'), table_name='condition_assessments')
    op.drop_index(op.f('ix_car_sale_history_car_id'), table_name='car_sale_history')
    op.drop_index(op.f('ix_auto_checks_car_id'), table_name='auto_checks')
    # ### end Alembic commands ###
