"""temp_migration

Revision ID: edd45a9efaa6
Revises: f0bc7583c33f
Create Date: 2025-05-09 12:00:21.253422

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "edd45a9efaa6"
down_revision: Union[str, None] = "f0bc7583c33f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("roi", sa.Integer(), nullable=False),
        sa.Column("profit_margin", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roi_id"), "roi", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_roi_id"), table_name="roi")
    op.drop_table("roi")
    # ### end Alembic commands ###
