"""temp_migration

Revision ID: f0bc7583c33f
Revises: d0f3d9a22b90
Create Date: 2025-05-05 12:25:18.239166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0bc7583c33f'
down_revision: Union[str, None] = 'd0f3d9a22b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_checks_id'), 'auto_checks', ['id'], unique=False)
    op.add_column('cars', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'link')
    op.drop_index(op.f('ix_auto_checks_id'), table_name='auto_checks')
    op.drop_table('auto_checks')
    # ### end Alembic commands ###
